"""create travel models

Revision ID: 0dbda10269c2
Revises: b12268fad676
Create Date: 2026-08-13 22:01:40.130587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dbda10269c2'
down_revision: Union[str, Sequence[str], None] = 'b12268fad676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('price_per_night', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_number')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('price_per_day', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('room_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_bookings_room_id'), 'room_bookings', ['room_id'], unique=False)
    op.create_index(op.f('ix_room_bookings_status'), 'room_bookings', ['status'], unique=False)
    op.create_table('tour_departures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tour_package_id', sa.UUID(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tour_package_id'], ['tour_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_departures_departure_date'), 'tour_departures', ['departure_date'], unique=False)
    op.create_index(op.f('ix_tour_departures_tour_package_id'), 'tour_departures', ['tour_package_id'], unique=False)
    op.create_table('tour_gallery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tour_package_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tour_package_id'], ['tour_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_gallery_tour_package_id'), 'tour_gallery', ['tour_package_id'], unique=False)
    op.create_table('tour_highlights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tour_package_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tour_package_id'], ['tour_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_highlights_tour_package_id'), 'tour_highlights', ['tour_package_id'], unique=False)
    op.create_table('tour_itinerary_days',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tour_package_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tour_package_id'], ['tour_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_itinerary_days_tour_package_id'), 'tour_itinerary_days', ['tour_package_id'], unique=False)
    op.create_table('tour_route_stops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tour_package_id', sa.UUID(), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tour_package_id'], ['tour_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_route_stops_tour_package_id'), 'tour_route_stops', ['tour_package_id'], unique=False)
    op.create_table('vehicle_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_bookings_status'), 'vehicle_bookings', ['status'], unique=False)
    op.create_index(op.f('ix_vehicle_bookings_vehicle_id'), 'vehicle_bookings', ['vehicle_id'], unique=False)
    op.add_column('custom_tour_requests', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('custom_tour_requests', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_custom_tour_requests_status'), 'custom_tour_requests', ['status'], unique=False)
    op.create_index(op.f('ix_custom_tour_requests_visitor_id'), 'custom_tour_requests', ['visitor_id'], unique=False)
    op.add_column('reviews', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_reviews_package_id'), 'reviews', ['package_id'], unique=False)
    op.create_index(op.f('ix_reviews_visitor_id'), 'reviews', ['visitor_id'], unique=False)
    op.create_check_constraint('ck_reviews_rating', 'reviews', 'rating >= 1 AND rating <= 5')
    op.add_column('tour_packages', sa.Column('code', sa.String(length=50), nullable=False))
    op.add_column('tour_packages', sa.Column('season', sa.String(length=100), nullable=True))
    op.add_column('tour_packages', sa.Column('accent', sa.String(length=20), nullable=True))
    op.add_column('tour_packages', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('tour_packages', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tour_packages', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_tour_packages_code'), 'tour_packages', ['code'], unique=True)
    op.create_index(op.f('ix_visitor_events_created_at'), 'visitor_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_visitor_events_event_name'), 'visitor_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_visitor_events_session_id'), 'visitor_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_visitor_events_visitor_id'), 'visitor_events', ['visitor_id'], unique=False)
    op.create_index(op.f('ix_visitor_sessions_started_at'), 'visitor_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_visitor_sessions_visitor_id'), 'visitor_sessions', ['visitor_id'], unique=False)
    op.drop_constraint(op.f('visitors_fingerprint_key'), 'visitors', type_='unique')
    op.create_index(op.f('ix_visitors_fingerprint'), 'visitors', ['fingerprint'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitors_fingerprint'), table_name='visitors')
    op.create_unique_constraint(op.f('visitors_fingerprint_key'), 'visitors', ['fingerprint'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_visitor_sessions_visitor_id'), table_name='visitor_sessions')
    op.drop_index(op.f('ix_visitor_sessions_started_at'), table_name='visitor_sessions')
    op.drop_index(op.f('ix_visitor_events_visitor_id'), table_name='visitor_events')
    op.drop_index(op.f('ix_visitor_events_session_id'), table_name='visitor_events')
    op.drop_index(op.f('ix_visitor_events_event_name'), table_name='visitor_events')
    op.drop_index(op.f('ix_visitor_events_created_at'), table_name='visitor_events')
    op.drop_index(op.f('ix_tour_packages_code'), table_name='tour_packages')
    op.drop_column('tour_packages', 'updated_at')
    op.drop_column('tour_packages', 'created_at')
    op.drop_column('tour_packages', 'image')
    op.drop_column('tour_packages', 'accent')
    op.drop_column('tour_packages', 'season')
    op.drop_column('tour_packages', 'code')
    op.drop_constraint('ck_reviews_rating', 'reviews', type_='check')
    op.drop_index(op.f('ix_reviews_visitor_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_package_id'), table_name='reviews')
    op.drop_column('reviews', 'created_at')
    op.drop_index(op.f('ix_custom_tour_requests_visitor_id'), table_name='custom_tour_requests')
    op.drop_index(op.f('ix_custom_tour_requests_status'), table_name='custom_tour_requests')
    op.drop_column('custom_tour_requests', 'updated_at')
    op.drop_column('custom_tour_requests', 'created_at')
    op.drop_index(op.f('ix_vehicle_bookings_vehicle_id'), table_name='vehicle_bookings')
    op.drop_index(op.f('ix_vehicle_bookings_status'), table_name='vehicle_bookings')
    op.drop_table('vehicle_bookings')
    op.drop_index(op.f('ix_tour_route_stops_tour_package_id'), table_name='tour_route_stops')
    op.drop_table('tour_route_stops')
    op.drop_index(op.f('ix_tour_itinerary_days_tour_package_id'), table_name='tour_itinerary_days')
    op.drop_table('tour_itinerary_days')
    op.drop_index(op.f('ix_tour_highlights_tour_package_id'), table_name='tour_highlights')
    op.drop_table('tour_highlights')
    op.drop_index(op.f('ix_tour_gallery_tour_package_id'), table_name='tour_gallery')
    op.drop_table('tour_gallery')
    op.drop_index(op.f('ix_tour_departures_tour_package_id'), table_name='tour_departures')
    op.drop_index(op.f('ix_tour_departures_departure_date'), table_name='tour_departures')
    op.drop_table('tour_departures')
    op.drop_index(op.f('ix_room_bookings_status'), table_name='room_bookings')
    op.drop_index(op.f('ix_room_bookings_room_id'), table_name='room_bookings')
    op.drop_table('room_bookings')
    op.drop_table('vehicles')
    op.drop_table('rooms')
    # ### end Alembic commands ###
