"""add document and referral  modles

Revision ID: 11a17ae79ed1
Revises: df13c404c735
Create Date: 2026-08-26 01:15:53.263831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a17ae79ed1'
down_revision: Union[str, Sequence[str], None] = 'df13c404c735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The app has historically stored legacy actor_type='USER' for admin/staff sessions.
    # PostgreSQL requires enum values to be added in an autocommit block before row updates.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE actor_type ADD VALUE IF NOT EXISTS 'ADMIN'")
        op.execute("ALTER TYPE actor_type ADD VALUE IF NOT EXISTS 'STAFF'")

    op.execute("UPDATE auth_sessions SET actor_type = 'ADMIN' WHERE actor_type::text = 'USER'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('document_code', sa.String(length=30), nullable=False),
    sa.Column('document_type', sa.Enum('ID_PROOF', 'ADDRESS_PROOF', 'TOUR_DOCUMENT', 'OTHER', name='document_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by_customer_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('deleted_by_customer_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by_customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_customer_id'), 'documents', ['customer_id'], unique=False)
    op.create_index(op.f('ix_documents_deleted_by_customer_id'), 'documents', ['deleted_by_customer_id'], unique=False)
    op.create_index(op.f('ix_documents_deleted_by_user_id'), 'documents', ['deleted_by_user_id'], unique=False)
    op.create_index(op.f('ix_documents_document_code'), 'documents', ['document_code'], unique=True)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by_customer_id'), 'documents', ['uploaded_by_customer_id'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by_user_id'), 'documents', ['uploaded_by_user_id'], unique=False)
    op.create_table('referrals',
    sa.Column('referrer_customer_id', sa.UUID(), nullable=False),
    sa.Column('referred_customer_id', sa.UUID(), nullable=False),
    sa.Column('referral_code', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONVERTED', 'REWARDED', 'EXPIRED', 'CANCELLED', name='referral_status'), nullable=False),
    sa.Column('reward_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reward_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('referrer_customer_id <> referred_customer_id', name='ck_referral_no_self_referral'),
    sa.ForeignKeyConstraint(['referred_customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], unique=True)
    op.create_index(op.f('ix_referrals_referred_customer_id'), 'referrals', ['referred_customer_id'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_customer_id'), 'referrals', ['referrer_customer_id'], unique=False)
    op.create_index(op.f('ix_referrals_status'), 'referrals', ['status'], unique=False)
    op.create_check_constraint('ck_auth_session_actor_owner', 'auth_sessions', "\n        (\n            actor_type IN ('ADMIN', 'STAFF')\n            AND user_id IS NOT NULL\n            AND customer_id IS NULL\n        )\n        OR\n        (\n            actor_type = 'CUSTOMER'\n            AND customer_id IS NOT NULL\n            AND user_id IS NULL\n        )\n        ")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_auth_session_actor_owner', 'auth_sessions', type_='check')
    op.drop_index(op.f('ix_referrals_status'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referrer_customer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_customer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referral_code'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_documents_uploaded_by_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_uploaded_by_customer_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_code'), table_name='documents')
    op.drop_index(op.f('ix_documents_deleted_by_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_deleted_by_customer_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_customer_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
