"""fix some travel tour realated models

Revision ID: 20f9cf1ae026
Revises: d8d3b3b40f84
Create Date: 2026-09-10 18:19:13.965024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f9cf1ae026'
down_revision: Union[str, Sequence[str], None] = 'd8d3b3b40f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_departures', 'price')

    # Add columns as nullable first so existing tour_variants rows do not violate
    # the NOT NULL constraint during the data migration.
    op.add_column('tour_variants', sa.Column('list_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tour_variants', sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=True))

    # Backfill the new columns from the now-legacy base_price column, which is
    # the data source present in the table before this revision reshapes it.
    op.execute(
        """
        UPDATE tour_variants
        SET list_price = COALESCE(base_price, 0),
            selling_price = COALESCE(base_price, 0)
        WHERE list_price IS NULL OR selling_price IS NULL
        """
    )

    # Enforce the intended non-null contract after rows have been materialized.
    op.alter_column('tour_variants', 'list_price', existing_type=sa.Numeric(precision=10, scale=2), nullable=False)
    op.alter_column('tour_variants', 'selling_price', existing_type=sa.Numeric(precision=10, scale=2), nullable=False)

    op.drop_column('tour_variants', 'base_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_variants', sa.Column('base_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('tour_variants', 'selling_price')
    op.drop_column('tour_variants', 'list_price')
    op.add_column('tour_departures', sa.Column('price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
