"""Initial schema

Revision ID: 30817af8ec10
Revises: 8b0822952a14
Create Date: 2026-08-14 18:06:58.053802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30817af8ec10'
down_revision: Union[str, Sequence[str], None] = '8b0822952a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_reviews_visitor_id'), table_name='reviews')
    op.create_index(op.f('ix_reviews_customer_id'), 'reviews', ['customer_id'], unique=False)
    op.drop_constraint(op.f('reviews_visitor_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.drop_column('reviews', 'visitor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('visitor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_visitor_id_fkey'), 'reviews', 'visitors', ['visitor_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_reviews_customer_id'), table_name='reviews')
    op.create_index(op.f('ix_reviews_visitor_id'), 'reviews', ['visitor_id'], unique=False)
    op.drop_column('reviews', 'customer_id')
    # ### end Alembic commands ###
