"""update travel database

Revision ID: 331314bca490
Revises: 4a63850aeba4
Create Date: 2026-08-13 22:38:28.745968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '331314bca490'
down_revision: Union[str, Sequence[str], None] = '4a63850aeba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitors', sa.Column('lead_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_visitors_lead_id'), 'visitors', ['lead_id'], unique=False)
    op.create_foreign_key(None, 'visitors', 'leads', ['lead_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visitors', type_='foreignkey')
    op.drop_index(op.f('ix_visitors_lead_id'), table_name='visitors')
    op.drop_column('visitors', 'lead_id')
    # ### end Alembic commands ###
