"""change tour_variant model

Revision ID: 33da5cfef073
Revises: e8c99ed1ab5f
Create Date: 2026-08-22 00:38:47.851826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33da5cfef073'
down_revision: Union[str, Sequence[str], None] = 'e8c99ed1ab5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_variants', 'currency')
    op.drop_column('tour_variants', 'season_type')
    op.drop_column('tour_variants', 'key')
    op.drop_column('tour_variants', 'display_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_variants', sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tour_variants', sa.Column('key', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tour_variants', sa.Column('season_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tour_variants', sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'INR'::character varying"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
