"""update referral models

Revision ID: 406962d75b52
Revises: 5a1ee1eb2633
Create Date: 2026-09-16 14:03:49.075411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '406962d75b52'
down_revision: Union[str, Sequence[str], None] = '5a1ee1eb2633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_reward_configs',
    sa.Column('default_reward_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('booking_window_days', sa.Integer(), nullable=False),
    sa.Column('updated_by_account_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_reward_configs_updated_by_account_id'), 'referral_reward_configs', ['updated_by_account_id'], unique=False)
    op.create_table('referral_reward_history',
    sa.Column('referral_id', sa.UUID(), nullable=False),
    sa.Column('approved_reward_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('credit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_account_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_reward_history_approved_by_account_id'), 'referral_reward_history', ['approved_by_account_id'], unique=False)
    op.create_index(op.f('ix_referral_reward_history_referral_id'), 'referral_reward_history', ['referral_id'], unique=False)
    op.add_column('referrals', sa.Column('default_reward_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('referrals', sa.Column('booking_window_days', sa.Integer(), nullable=True))
    op.add_column('referrals', sa.Column('booking_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('referrals', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('referrals', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('referrals', 'reward_amount')
    op.drop_column('referrals', 'reward_issued_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('reward_issued_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('reward_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.drop_column('referrals', 'is_active')
    op.drop_column('referrals', 'updated_at')
    op.drop_column('referrals', 'booking_completed_at')
    op.drop_column('referrals', 'booking_window_days')
    op.drop_column('referrals', 'default_reward_amount')
    op.drop_index(op.f('ix_referral_reward_history_referral_id'), table_name='referral_reward_history')
    op.drop_index(op.f('ix_referral_reward_history_approved_by_account_id'), table_name='referral_reward_history')
    op.drop_table('referral_reward_history')
    op.drop_index(op.f('ix_referral_reward_configs_updated_by_account_id'), table_name='referral_reward_configs')
    op.drop_table('referral_reward_configs')
    # ### end Alembic commands ###
