"""remove note from  referral models

Revision ID: 49219a6996f4
Revises: 406962d75b52
Create Date: 2026-09-16 14:09:31.633080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49219a6996f4'
down_revision: Union[str, Sequence[str], None] = '406962d75b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referral_reward_history', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_reward_history', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
