"""enhance tour offer models

Revision ID: 4cb010bd1860
Revises: 20f9cf1ae026
Create Date: 2026-09-10 21:06:18.769268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb010bd1860'
down_revision: Union[str, Sequence[str], None] = '20f9cf1ae026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tour_offer_package_variant', 'tour_offer_packages', ['offer_id', 'variant_id'])
    op.drop_index(op.f('ix_tour_offers_code'), table_name='tour_offers')
    op.drop_column('tour_offers', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_offers', sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_tour_offers_code'), 'tour_offers', ['code'], unique=True)
    op.drop_constraint('uq_tour_offer_package_variant', 'tour_offer_packages', type_='unique')
    # ### end Alembic commands ###
