"""Remove room model and add quotation hotel,vehicle models

Revision ID: 4e7e84dbc552
Revises: 9a0b1c2d3e4f
Create Date: 2026-09-21 22:22:28.937195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e7e84dbc552'
down_revision: Union[str, Sequence[str], None] = '9a0b1c2d3e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation_hotels',
    sa.Column('quotation_item_id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=True),
    sa.Column('hotel_name', sa.String(length=255), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_item_id'], ['quotation_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_hotels_hotel_id'), 'quotation_hotels', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_quotation_hotels_quotation_item_id'), 'quotation_hotels', ['quotation_item_id'], unique=True)
    op.create_table('quotation_vehicles',
    sa.Column('quotation_item_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_name', sa.String(length=255), nullable=False),
    sa.Column('vehicle_type', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quotation_item_id'], ['quotation_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_vehicles_quotation_item_id'), 'quotation_vehicles', ['quotation_item_id'], unique=True)
    op.create_index(op.f('ix_quotation_vehicles_vehicle_id'), 'quotation_vehicles', ['vehicle_id'], unique=False)
    op.drop_index(op.f('ix_room_allocations_booking_id'), table_name='room_allocations')
    op.drop_index(op.f('ix_room_allocations_room_id'), table_name='room_allocations')
    op.drop_table('room_allocations')
    op.drop_index(op.f('ix_vehicle_allocations_booking_id'), table_name='vehicle_allocations')
    op.drop_index(op.f('ix_vehicle_allocations_vehicle_id'), table_name='vehicle_allocations')
    op.drop_table('vehicle_allocations')
    op.drop_constraint(op.f('fk_quotations_room_id_rooms'), 'quotations', type_='foreignkey')
    op.drop_index(op.f('ix_rooms_hotel_id'), table_name='rooms')
    op.drop_table('rooms')
    op.create_index(op.f('ix_hotels_category'), 'hotels', ['category'], unique=False)
    op.drop_index(op.f('ix_quotations_destination_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_hotel_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_offer_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_package_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_room_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_variant_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_vehicle_id'), table_name='quotations')
    op.drop_constraint(op.f('quotations_package_id_fkey'), 'quotations', type_='foreignkey')
    op.drop_constraint(op.f('fk_quotations_offer_id_tour_offers'), 'quotations', type_='foreignkey')
    op.drop_constraint(op.f('fk_quotations_vehicle_id_vehicles'), 'quotations', type_='foreignkey')
    op.drop_constraint(op.f('quotations_destination_id_fkey'), 'quotations', type_='foreignkey')
    op.drop_constraint(op.f('fk_quotations_hotel_id_hotels'), 'quotations', type_='foreignkey')
    op.drop_constraint(op.f('quotations_variant_id_fkey'), 'quotations', type_='foreignkey')
    op.drop_constraint(op.f('ck_quotation_adult_count_non_negative'), 'quotations', type_='check')
    op.drop_constraint(op.f('ck_quotation_child_count_non_negative'), 'quotations', type_='check')
    op.drop_constraint(op.f('ck_quotation_has_traveller'), 'quotations', type_='check')
    op.drop_constraint(op.f('ck_quotation_senior_count_non_negative'), 'quotations', type_='check')
    op.drop_column('quotations', 'meal_plan')
    op.drop_column('quotations', 'package_id')
    op.drop_column('quotations', 'room_count')
    op.drop_column('quotations', 'variant_id')
    op.drop_column('quotations', 'senior_count')
    op.drop_column('quotations', 'adult_count')
    op.drop_column('quotations', 'hotel_id')
    op.drop_column('quotations', 'room_id')
    op.drop_column('quotations', 'child_count')
    op.drop_column('quotations', 'destination_id')
    op.drop_column('quotations', 'offer_id')
    op.drop_column('quotations', 'vehicle_count')
    op.drop_column('quotations', 'vehicle_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('vehicle_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('quotations', sa.Column('vehicle_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('quotations', sa.Column('offer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('quotations', sa.Column('destination_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('quotations', sa.Column('child_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('quotations', sa.Column('room_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('quotations', sa.Column('hotel_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('quotations', sa.Column('adult_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('quotations', sa.Column('senior_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('quotations', sa.Column('variant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('quotations', sa.Column('room_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('quotations', sa.Column('package_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('quotations', sa.Column('meal_plan', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_check_constraint(op.f('ck_quotation_senior_count_non_negative'), 'quotations', 'senior_count >= 0')
    op.create_check_constraint(op.f('ck_quotation_has_traveller'), 'quotations', '(adult_count + child_count + senior_count) > 0')
    op.create_check_constraint(op.f('ck_quotation_child_count_non_negative'), 'quotations', 'child_count >= 0')
    op.create_check_constraint(op.f('ck_quotation_adult_count_non_negative'), 'quotations', 'adult_count >= 0')
    op.create_foreign_key(op.f('quotations_variant_id_fkey'), 'quotations', 'tour_variants', ['variant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_quotations_hotel_id_hotels'), 'quotations', 'hotels', ['hotel_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('quotations_destination_id_fkey'), 'quotations', 'destinations', ['destination_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_quotations_room_id_rooms'), 'quotations', 'rooms', ['room_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_quotations_vehicle_id_vehicles'), 'quotations', 'vehicles', ['vehicle_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_quotations_offer_id_tour_offers'), 'quotations', 'tour_offers', ['offer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('quotations_package_id_fkey'), 'quotations', 'tour_packages', ['package_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_quotations_vehicle_id'), 'quotations', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_quotations_variant_id'), 'quotations', ['variant_id'], unique=False)
    op.create_index(op.f('ix_quotations_room_id'), 'quotations', ['room_id'], unique=False)
    op.create_index(op.f('ix_quotations_package_id'), 'quotations', ['package_id'], unique=False)
    op.create_index(op.f('ix_quotations_offer_id'), 'quotations', ['offer_id'], unique=False)
    op.create_index(op.f('ix_quotations_hotel_id'), 'quotations', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_quotations_destination_id'), 'quotations', ['destination_id'], unique=False)
    op.drop_index(op.f('ix_hotels_category'), table_name='hotels')
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('room_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('room_type', postgresql.ENUM('SINGLE', 'DOUBLE', 'TWIN', 'TRIPLE', 'FAMILY', 'SUITE', 'DELUXE', 'EXECUTIVE', 'PRESIDENTIAL', name='room_type'), autoincrement=False, nullable=True),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_per_night', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('hotel_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('room_image', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('rooms_hotel_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('rooms_pkey')),
    sa.UniqueConstraint('room_number', name=op.f('rooms_room_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_rooms_hotel_id'), 'rooms', ['hotel_id'], unique=False)
    op.create_table('vehicle_allocations',
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('vehicle_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('vehicle_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('registration_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('driver_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('driver_mobile', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('vehicle_allocations_booking_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('vehicle_allocations_vehicle_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicle_allocations_pkey'))
    )
    op.create_index(op.f('ix_vehicle_allocations_vehicle_id'), 'vehicle_allocations', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_vehicle_allocations_booking_id'), 'vehicle_allocations', ['booking_id'], unique=False)
    op.create_table('room_allocations',
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('room_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('room_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('occupant_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('room_allocations_booking_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('room_allocations_room_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('room_allocations_pkey'))
    )
    op.create_index(op.f('ix_room_allocations_room_id'), 'room_allocations', ['room_id'], unique=False)
    op.create_index(op.f('ix_room_allocations_booking_id'), 'room_allocations', ['booking_id'], unique=False)
    op.drop_index(op.f('ix_quotation_vehicles_vehicle_id'), table_name='quotation_vehicles')
    op.drop_index(op.f('ix_quotation_vehicles_quotation_item_id'), table_name='quotation_vehicles')
    op.drop_table('quotation_vehicles')
    op.drop_index(op.f('ix_quotation_hotels_quotation_item_id'), table_name='quotation_hotels')
    op.drop_index(op.f('ix_quotation_hotels_hotel_id'), table_name='quotation_hotels')
    op.drop_table('quotation_hotels')
    # ### end Alembic commands ###
