"""improve financial models

Revision ID: 5a1ee1eb2633
Revises: a7b8c9d0e1f2
Create Date: 2026-09-14 18:41:31.793637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a1ee1eb2633'
down_revision: Union[str, Sequence[str], None] = 'a7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_financial_accounts_account_code'), 'financial_accounts', ['account_code'], unique=False)
    op.create_index(op.f('ix_financial_accounts_account_type'), 'financial_accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_financial_accounts_owner_type'), 'financial_accounts', ['owner_type'], unique=False)
    op.create_index(op.f('ix_financial_transaction_entries_account_id'), 'financial_transaction_entries', ['account_id'], unique=False)
    op.create_index(op.f('ix_financial_transaction_entries_transaction_id'), 'financial_transaction_entries', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_booking_id'), 'financial_transactions', ['booking_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_category'), 'financial_transactions', ['category'], unique=False)
    op.create_index(op.f('ix_financial_transactions_customer_id'), 'financial_transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_enquiry_id'), 'financial_transactions', ['enquiry_id'], unique=False)
    op.create_index('ix_financial_transactions_external_reference', 'financial_transactions', ['external_reference'], unique=False)
    op.create_index(op.f('ix_financial_transactions_quotation_id'), 'financial_transactions', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_status'), 'financial_transactions', ['status'], unique=False)
    op.create_index('ix_financial_transactions_transaction_date', 'financial_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_financial_transactions_transaction_type'), 'financial_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_financial_transactions_vendor_id'), 'financial_transactions', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_transactions_vendor_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_transaction_type'), table_name='financial_transactions')
    op.drop_index('ix_financial_transactions_transaction_date', table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_status'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_quotation_id'), table_name='financial_transactions')
    op.drop_index('ix_financial_transactions_external_reference', table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_enquiry_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_customer_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_category'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_booking_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transaction_entries_transaction_id'), table_name='financial_transaction_entries')
    op.drop_index(op.f('ix_financial_transaction_entries_account_id'), table_name='financial_transaction_entries')
    op.drop_index(op.f('ix_financial_accounts_owner_type'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_account_type'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_account_code'), table_name='financial_accounts')
    # ### end Alembic commands ###
