"""change enquiry model

Revision ID: 60633c12b803
Revises: 9e8f7a6b5c4d
Create Date: 2026-09-16 18:06:54.605028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60633c12b803'
down_revision: Union[str, Sequence[str], None] = '9e8f7a6b5c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('vehicle_count', sa.Integer(), nullable=True))
    op.drop_column('enquiries', 'vehicle_type')
    op.drop_column('enquiries', 'subject')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('subject', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('enquiries', sa.Column('vehicle_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('enquiries', 'vehicle_count')
    # ### end Alembic commands ###
