"""create travel models

Revision ID: 62e7f057ab70
Revises: c1d2e3f4a5b6
Create Date: 2026-08-16 00:40:51.540464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e7f057ab70'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    oauth_purpose = sa.Enum(
        'ADMIN_LOGIN',
        'CUSTOMER_LOGIN',
        'CUSTOMER_LINK',
        name='oauth_purpose',
    )
    oauth_purpose.create(op.get_bind(), checkfirst=True)

    op.alter_column('google_oauth_states', 'state_token',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Random CSRF state token',
               existing_nullable=False)
    op.alter_column('google_oauth_states', 'purpose',
               existing_type=sa.VARCHAR(length=30),
               type_=oauth_purpose,
               comment=None,
               existing_comment='ADMIN_LOGIN, CUSTOMER_LOGIN, CUSTOMER_LINK',
               existing_nullable=False,
               postgresql_using='purpose::oauth_purpose')
    op.alter_column('google_oauth_states', 'redirect_uri',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Where to redirect after auth',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    oauth_purpose = sa.Enum(
        'ADMIN_LOGIN',
        'CUSTOMER_LOGIN',
        'CUSTOMER_LINK',
        name='oauth_purpose',
    )

    op.alter_column('google_oauth_states', 'redirect_uri',
               existing_type=sa.TEXT(),
               comment='Where to redirect after auth',
               existing_nullable=True)
    op.alter_column('google_oauth_states', 'purpose',
               existing_type=oauth_purpose,
               type_=sa.VARCHAR(length=30),
               comment='ADMIN_LOGIN, CUSTOMER_LOGIN, CUSTOMER_LINK',
               existing_nullable=False,
               postgresql_using='purpose::text')
    op.alter_column('google_oauth_states', 'state_token',
               existing_type=sa.VARCHAR(length=255),
               comment='Random CSRF state token',
               existing_nullable=False)
    oauth_purpose.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
