"""update travel database

Revision ID: 6afe40f9288f
Revises: 1ea1e27a822b
Create Date: 2026-08-13 22:06:54.323245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6afe40f9288f'
down_revision: Union[str, Sequence[str], None] = '1ea1e27a822b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_packages', 'accent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_packages', sa.Column('accent', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
