"""create CustomerTour model

Revision ID: 762d5127acc8
Revises: d4e5f6a7b8c9
Create Date: 2026-08-25 20:40:45.199962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '762d5127acc8'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_tours',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('enquiry_id', sa.UUID(), nullable=True),
    sa.Column('tour_name', sa.String(length=200), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=True),
    sa.Column('travel_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('pax_no', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='customer_tour_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['package_id'], ['tour_packages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['tour_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_tours_created_by_user_id'), 'customer_tours', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_customer_tours_customer_id'), 'customer_tours', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_tours_enquiry_id'), 'customer_tours', ['enquiry_id'], unique=False)
    op.create_index(op.f('ix_customer_tours_package_id'), 'customer_tours', ['package_id'], unique=False)
    op.create_index(op.f('ix_customer_tours_status'), 'customer_tours', ['status'], unique=False)
    op.create_index(op.f('ix_customer_tours_variant_id'), 'customer_tours', ['variant_id'], unique=False)
    op.alter_column('lead_activities', 'lead_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lead_activities', 'lead_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_customer_tours_variant_id'), table_name='customer_tours')
    op.drop_index(op.f('ix_customer_tours_status'), table_name='customer_tours')
    op.drop_index(op.f('ix_customer_tours_package_id'), table_name='customer_tours')
    op.drop_index(op.f('ix_customer_tours_enquiry_id'), table_name='customer_tours')
    op.drop_index(op.f('ix_customer_tours_customer_id'), table_name='customer_tours')
    op.drop_index(op.f('ix_customer_tours_created_by_user_id'), table_name='customer_tours')
    op.drop_table('customer_tours')
    # ### end Alembic commands ###
