"""create travel models

Revision ID: 777ddcf11128
Revises: 9337705be218
Create Date: 2026-08-15 17:53:10.711066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '777ddcf11128'
down_revision: Union[str, Sequence[str], None] = '9337705be218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_oauth_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state_token', sa.String(length=255), nullable=False, comment='Random CSRF state token'),
    sa.Column('purpose', sa.String(length=30), nullable=False, comment='ADMIN_LOGIN, CUSTOMER_LOGIN, CUSTOMER_LINK'),
    sa.Column('redirect_uri', sa.Text(), nullable=True, comment='Where to redirect after auth'),
    sa.Column('visitor_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_oauth_states_state_token'), 'google_oauth_states', ['state_token'], unique=True)
    op.create_index(op.f('ix_google_oauth_states_visitor_id'), 'google_oauth_states', ['visitor_id'], unique=False)
    op.create_table('otp_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False, comment='Mobile number or email being verified'),
    sa.Column('identifier_type', sa.String(length=10), nullable=False, comment='MOBILE or EMAIL'),
    sa.Column('otp_hash', sa.String(length=255), nullable=False, comment='Bcrypt-hashed OTP, never plaintext'),
    sa.Column('purpose', sa.String(length=30), nullable=False, comment='LOGIN, VERIFY_MOBILE, VERIFY_EMAIL'),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visitor_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_challenges_customer_id'), 'otp_challenges', ['customer_id'], unique=False)
    op.create_index(op.f('ix_otp_challenges_identifier'), 'otp_challenges', ['identifier'], unique=False)
    op.create_index(op.f('ix_otp_challenges_visitor_id'), 'otp_challenges', ['visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_challenges_visitor_id'), table_name='otp_challenges')
    op.drop_index(op.f('ix_otp_challenges_identifier'), table_name='otp_challenges')
    op.drop_index(op.f('ix_otp_challenges_customer_id'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_index(op.f('ix_google_oauth_states_visitor_id'), table_name='google_oauth_states')
    op.drop_index(op.f('ix_google_oauth_states_state_token'), table_name='google_oauth_states')
    op.drop_table('google_oauth_states')
    # ### end Alembic commands ###
