"""remove duplicated lead fields

Revision ID: 85f3f4c81ff7
Revises: a73237cafa48
Create Date: 2026-09-18 21:48:38.458784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85f3f4c81ff7'
down_revision: Union[str, Sequence[str], None] = 'a73237cafa48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_customer_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_mobile'), table_name='leads')
    op.drop_index(op.f('ix_leads_source'), table_name='leads')
    op.drop_index(op.f('ix_leads_visitor_id'), table_name='leads')
    op.drop_constraint(op.f('leads_customer_id_fkey'), 'leads', type_='foreignkey')
    op.drop_constraint(op.f('leads_visitor_id_fkey'), 'leads', type_='foreignkey')
    op.drop_column('leads', 'customer_id')
    op.drop_column('leads', 'email')
    op.drop_column('leads', 'whatsapp_opt_in')
    op.drop_column('leads', 'full_name')
    op.drop_column('leads', 'visitor_id')
    op.drop_column('leads', 'notes')
    op.drop_column('leads', 'source')
    op.drop_column('leads', 'mobile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('mobile', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('source', postgresql.ENUM('WEBSITE', 'WHATSAPP', 'PHONE', 'EMAIL', 'OFFLINE', 'IMPORT', 'REFERRAL', 'OTHER', name='lead_source'), autoincrement=False, nullable=False))
    op.add_column('leads', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('visitor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('leads', sa.Column('whatsapp_opt_in', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('leads', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('leads_visitor_id_fkey'), 'leads', 'visitors', ['visitor_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('leads_customer_id_fkey'), 'leads', 'accounts', ['customer_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_leads_visitor_id'), 'leads', ['visitor_id'], unique=False)
    op.create_index(op.f('ix_leads_source'), 'leads', ['source'], unique=False)
    op.create_index(op.f('ix_leads_mobile'), 'leads', ['mobile'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_customer_id'), 'leads', ['customer_id'], unique=False)
    # ### end Alembic commands ###
