"""initial schema

Revision ID: 8767edd7015c
Revises: 
Create Date: 2026-09-29 15:18:32.281515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8767edd7015c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', 'CUSTOMER', name='account_role'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_pic', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_code'), 'accounts', ['account_code'], unique=True)
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=False)
    op.create_index(op.f('ix_accounts_mobile'), 'accounts', ['mobile'], unique=False)
    op.create_index(op.f('ix_accounts_role'), 'accounts', ['role'], unique=False)
    op.create_index('uq_active_customer_email', 'accounts', ['email'], unique=True, postgresql_where=sa.text("role = 'CUSTOMER' AND is_active = true"), sqlite_where=sa.text("role = 'CUSTOMER' AND is_active = true"))
    op.create_index('uq_active_customer_mobile', 'accounts', ['mobile'], unique=True, postgresql_where=sa.text("role = 'CUSTOMER' AND is_active = true"), sqlite_where=sa.text("role = 'CUSTOMER' AND is_active = true"))
    op.create_index('uq_admin_email', 'accounts', ['email'], unique=True, postgresql_where=sa.text("role = 'ADMIN'"), sqlite_where=sa.text("role = 'ADMIN'"))
    op.create_index('uq_admin_mobile', 'accounts', ['mobile'], unique=True, postgresql_where=sa.text("role = 'ADMIN'"), sqlite_where=sa.text("role = 'ADMIN'"))
    op.create_index('uq_staff_email', 'accounts', ['email'], unique=True, postgresql_where=sa.text("role = 'STAFF'"), sqlite_where=sa.text("role = 'STAFF'"))
    op.create_index('uq_staff_mobile', 'accounts', ['mobile'], unique=True, postgresql_where=sa.text("role = 'STAFF'"), sqlite_where=sa.text("role = 'STAFF'"))
    op.create_table('destinations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('is_domestic', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_name'), 'destinations', ['name'], unique=False)
    op.create_index(op.f('ix_destinations_slug'), 'destinations', ['slug'], unique=True)
    op.create_table('financial_accounts',
    sa.Column('account_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('account_type', sa.Enum('ASSET', 'LIABILITY', 'REVENUE', 'EXPENSE', 'CASH', 'SAVINGS', 'CURRENT', 'LOAN', name='financial_account_type'), nullable=False),
    sa.Column('owner_type', sa.Enum('SYSTEM', 'CUSTOMER', 'VENDOR', name='financial_account_owner_type'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_code', name='uq_financial_accounts_account_code'),
    sa.UniqueConstraint('owner_type', 'owner_id', 'account_type', name='uq_financial_accounts_owner_type_id_type')
    )
    op.create_index(op.f('ix_financial_accounts_account_code'), 'financial_accounts', ['account_code'], unique=False)
    op.create_index(op.f('ix_financial_accounts_account_type'), 'financial_accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_financial_accounts_owner_type'), 'financial_accounts', ['owner_type'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('action_url', sa.String(length=1000), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('recipient_ids', sa.JSON().with_variant(postgresql.ARRAY(sa.UUID()), 'postgresql'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_expires_at'), 'notifications', ['expires_at'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_table('tour_offers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'EXPIRED', name='offer_status'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FIXED', name='offer_discount_type'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_booking_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('per_customer_limit', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('discount_value >= 0', name='ck_tour_offer_discount_value_non_negative'),
    sa.CheckConstraint('per_customer_limit IS NULL OR per_customer_limit > 0', name='ck_tour_offer_customer_limit_positive'),
    sa.CheckConstraint('usage_limit IS NULL OR usage_limit > 0', name='ck_tour_offer_usage_limit_positive'),
    sa.CheckConstraint('valid_until > valid_from', name='ck_tour_offer_valid_dates'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('vehicle_image', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vehicle_type', sa.Enum('ANY', 'NONE', 'FOUR_SEATER', 'SIX_SEATER', 'TEMPO', name='vehicletype'), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('price_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index(op.f('ix_vehicles_vehicle_type'), 'vehicles', ['vehicle_type'], unique=False)
    op.create_table('vendors',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_sessions',
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_account_id'), 'auth_sessions', ['account_id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_refresh_token_hash'), 'auth_sessions', ['refresh_token_hash'], unique=True)
    op.create_table('customer_profiles',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_mobile', sa.String(length=20), nullable=True),
    sa.Column('source', sa.Enum('WEBSITE', 'WHATSAPP', 'PHONE', 'EMAIL', 'OFFLINE', 'IMPORT', 'REFERRAL', 'OTHER', name='lead_source'), nullable=False),
    sa.Column('special_discount_type', sa.Enum('PERCENTAGE', 'FIXED', name='discount_type'), nullable=True),
    sa.Column('special_discount', sa.String(length=50), nullable=True),
    sa.Column('referral_code', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_index(op.f('ix_customer_profiles_referral_code'), 'customer_profiles', ['referral_code'], unique=True)
    op.create_table('documents',
    sa.Column('document_type', sa.Enum('ID_PROOF', 'ADDRESS_PROOF', 'TOUR_DOCUMENT', 'OTHER', name='document_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by_account_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_account_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_customer_id'), 'documents', ['customer_id'], unique=False)
    op.create_index(op.f('ix_documents_deleted_by_account_id'), 'documents', ['deleted_by_account_id'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by_account_id'), 'documents', ['uploaded_by_account_id'], unique=False)
    op.create_table('hotels',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('BUDGET', 'STANDARD', 'DELUXE', 'LUXURY', name='hotel_category'), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_category'), 'hotels', ['category'], unique=False)
    op.create_index(op.f('ix_hotels_destination_id'), 'hotels', ['destination_id'], unique=False)
    op.create_table('notification_campaigns',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('is_delivered', sa.Boolean(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_campaigns_is_delivered'), 'notification_campaigns', ['is_delivered'], unique=False)
    op.create_index(op.f('ix_notification_campaigns_is_read'), 'notification_campaigns', ['is_read'], unique=False)
    op.create_index(op.f('ix_notification_campaigns_notification_id'), 'notification_campaigns', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notification_campaigns_recipient_id'), 'notification_campaigns', ['recipient_id'], unique=False)
    op.create_table('referral_reward_configs',
    sa.Column('default_reward_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('booking_window_days', sa.Integer(), nullable=False),
    sa.Column('updated_by_account_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_reward_configs_updated_by_account_id'), 'referral_reward_configs', ['updated_by_account_id'], unique=False)
    op.create_table('referrals',
    sa.Column('referrer_customer_id', sa.UUID(), nullable=False),
    sa.Column('referred_customer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REGISTERED', 'BOOKING_COMPLETED', 'REWARD_ELIGIBLE', 'REWARD_APPROVED', 'REWARD_CREDITED', 'EXPIRED', 'CANCELLED', 'BLOCKED', name='referral_status'), nullable=False),
    sa.Column('default_reward_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('booking_window_days', sa.Integer(), nullable=True),
    sa.Column('booking_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('referrer_customer_id <> referred_customer_id', name='ck_referral_no_self_referral'),
    sa.ForeignKeyConstraint(['referred_customer_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_customer_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_referred_customer_id'), 'referrals', ['referred_customer_id'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_customer_id'), 'referrals', ['referrer_customer_id'], unique=False)
    op.create_index(op.f('ix_referrals_status'), 'referrals', ['status'], unique=False)
    op.create_table('tour_packages',
    sa.Column('tour_code', sa.String(length=20), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('DOMESTIC', 'INTERNATIONAL', name='tourtype', native_enum=False, length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_packages_destination_id'), 'tour_packages', ['destination_id'], unique=False)
    op.create_index(op.f('ix_tour_packages_slug'), 'tour_packages', ['slug'], unique=True)
    op.create_index(op.f('ix_tour_packages_tour_code'), 'tour_packages', ['tour_code'], unique=True)
    op.create_table('visitors',
    sa.Column('visitor_code', sa.String(length=20), nullable=False),
    sa.Column('fingerprint', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitors_customer_id'), 'visitors', ['customer_id'], unique=False)
    op.create_index(op.f('ix_visitors_fingerprint'), 'visitors', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_visitors_visitor_code'), 'visitors', ['visitor_code'], unique=True)
    op.create_table('otp_challenges',
    sa.Column('identifier', sa.String(length=255), nullable=False, comment='Mobile number or email being verified'),
    sa.Column('identifier_type', sa.String(length=10), nullable=False, comment='MOBILE or EMAIL'),
    sa.Column('otp_hash', sa.String(length=255), nullable=False, comment='Bcrypt-hashed OTP, never plaintext'),
    sa.Column('purpose', sa.String(length=30), nullable=False, comment='LOGIN, VERIFY_MOBILE, VERIFY_EMAIL'),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visitor_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_challenges_customer_id'), 'otp_challenges', ['customer_id'], unique=False)
    op.create_index(op.f('ix_otp_challenges_identifier'), 'otp_challenges', ['identifier'], unique=False)
    op.create_index(op.f('ix_otp_challenges_visitor_id'), 'otp_challenges', ['visitor_id'], unique=False)
    op.create_table('referral_reward_history',
    sa.Column('referral_id', sa.UUID(), nullable=False),
    sa.Column('approved_reward_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('credit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_account_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_reward_history_approved_by_account_id'), 'referral_reward_history', ['approved_by_account_id'], unique=False)
    op.create_index(op.f('ix_referral_reward_history_referral_id'), 'referral_reward_history', ['referral_id'], unique=False)
    op.create_table('reviews',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.Column('review_gallery', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_reviews_rating'),
    sa.ForeignKeyConstraint(['customer_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['package_id'], ['tour_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_customer_id'), 'reviews', ['customer_id'], unique=False)
    op.create_index(op.f('ix_reviews_package_id'), 'reviews', ['package_id'], unique=False)
    op.create_table('tour_variants',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('season_name', sa.String(length=100), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('duration_nights', sa.Integer(), nullable=False),
    sa.Column('list_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('badge', sa.String(length=50), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['tour_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_variants_package_id'), 'tour_variants', ['package_id'], unique=False)
    op.create_index(op.f('ix_tour_variants_slug'), 'tour_variants', ['slug'], unique=True)
    op.create_index('uq_tour_variants_single_default_per_package', 'tour_variants', ['package_id'], unique=True, postgresql_where=sa.text('is_default = true'), sqlite_where=sa.text('is_default = 1'))
    op.create_table('tour_wishlists',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['tour_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'package_id', name='uq_tour_wishlist_customer_package')
    )
    op.create_index(op.f('ix_tour_wishlists_customer_id'), 'tour_wishlists', ['customer_id'], unique=False)
    op.create_index(op.f('ix_tour_wishlists_package_id'), 'tour_wishlists', ['package_id'], unique=False)
    op.create_table('visitor_sessions',
    sa.Column('visitor_id', sa.UUID(), nullable=False),
    sa.Column('landing_page', sa.Text(), nullable=True),
    sa.Column('exit_page', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('utm_term', sa.String(length=100), nullable=True),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_sessions_visitor_id'), 'visitor_sessions', ['visitor_id'], unique=False)
    op.create_table('enquiries',
    sa.Column('enquiry_code', sa.String(length=20), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('enquiry_type', sa.Enum('FIXED_TOUR', 'CUSTOM_TOUR', name='enquiry_type'), nullable=False),
    sa.Column('channel', sa.Enum('WEBSITE', 'WHATSAPP', 'APP', 'PHONE', 'EMAIL', 'OFFLINE', 'ADMIN', name='enquiry_channel'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'QUOTED', 'CONVERTED', 'CANCELLED', 'CLOSED', name='enquiry_status'), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('enquirer_name', sa.String(length=50), nullable=True),
    sa.Column('enquirer_phone', sa.String(length=20), nullable=True),
    sa.Column('enquirer_email', sa.String(length=255), nullable=True),
    sa.Column('hotel_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('travel_date', sa.Date(), nullable=True),
    sa.Column('travel_duration_day', sa.Integer(), nullable=True),
    sa.Column('travel_duration_night', sa.Integer(), nullable=True),
    sa.Column('adult_count', sa.Integer(), nullable=True),
    sa.Column('child_count', sa.Integer(), nullable=True),
    sa.Column('senior_count', sa.Integer(), nullable=True),
    sa.Column('room_count', sa.Integer(), nullable=True),
    sa.Column('vehicle_count', sa.Integer(), nullable=True),
    sa.Column('meal_plan', sa.Enum('ANY', 'NONE', 'CP', 'MAP', 'AP', name='meal_plan'), nullable=True),
    sa.Column('budget_min', sa.Integer(), nullable=True),
    sa.Column('budget_max', sa.Integer(), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['package_id'], ['tour_packages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['tour_variants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enquiries_customer_id'), 'enquiries', ['customer_id'], unique=False)
    op.create_index(op.f('ix_enquiries_destination_id'), 'enquiries', ['destination_id'], unique=False)
    op.create_index(op.f('ix_enquiries_enquirer_email'), 'enquiries', ['enquirer_email'], unique=False)
    op.create_index(op.f('ix_enquiries_enquiry_code'), 'enquiries', ['enquiry_code'], unique=True)
    op.create_index(op.f('ix_enquiries_hotel_id'), 'enquiries', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_enquiries_package_id'), 'enquiries', ['package_id'], unique=False)
    op.create_index(op.f('ix_enquiries_status'), 'enquiries', ['status'], unique=False)
    op.create_index(op.f('ix_enquiries_variant_id'), 'enquiries', ['variant_id'], unique=False)
    op.create_index(op.f('ix_enquiries_vehicle_id'), 'enquiries', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_enquiries_visitor_id'), 'enquiries', ['visitor_id'], unique=False)
    op.create_table('tour_departures',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('available_seats >= 0 AND available_seats <= total_seats', name='ck_departure_available_seats_valid'),
    sa.CheckConstraint('total_seats >= 0', name='ck_departure_total_seats_non_negative'),
    sa.ForeignKeyConstraint(['variant_id'], ['tour_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_departures_departure_date'), 'tour_departures', ['departure_date'], unique=False)
    op.create_index(op.f('ix_tour_departures_variant_id'), 'tour_departures', ['variant_id'], unique=False)
    op.create_table('tour_details',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('banner', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gallery', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inclusions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exclusions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('itinerary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('route_stops', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['tour_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_details_variant_id'), 'tour_details', ['variant_id'], unique=True)
    op.create_table('tour_offer_packages',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['tour_offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['tour_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_id', 'variant_id', name='uq_tour_offer_package_variant')
    )
    op.create_index(op.f('ix_tour_offer_packages_offer_id'), 'tour_offer_packages', ['offer_id'], unique=False)
    op.create_index(op.f('ix_tour_offer_packages_variant_id'), 'tour_offer_packages', ['variant_id'], unique=False)
    op.create_table('visitor_events',
    sa.Column('visitor_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('page', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['visitor_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_events_event_name'), 'visitor_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_visitor_events_session_id'), 'visitor_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_visitor_events_visitor_id'), 'visitor_events', ['visitor_id'], unique=False)
    op.create_table('leads',
    sa.Column('lead_code', sa.String(length=20), nullable=False),
    sa.Column('enquiry_id', sa.UUID(), nullable=False),
    sa.Column('assigned_account_id', sa.UUID(), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'FOLLOW_UP', 'QUALIFIED', 'CONVERTED', 'LOST', name='lead_status'), nullable=False),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qualified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lost_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lost_reason', sa.Enum('PRICE_TOO_HIGH', 'BUDGET_ISSUE', 'TRAVEL_CANCELLED', 'CHANGED_DESTINATION', 'BOOKED_ELSEWHERE', 'NO_RESPONSE', 'DATES_UNAVAILABLE', 'NOT_INTERESTED', 'DUPLICATE', 'OTHER', name='lead_lost_reason'), nullable=True),
    sa.Column('lost_reason_notes', sa.String(length=1000), nullable=True),
    sa.Column('qualification_notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_assigned_account_id'), 'leads', ['assigned_account_id'], unique=False)
    op.create_index(op.f('ix_leads_enquiry_id'), 'leads', ['enquiry_id'], unique=True)
    op.create_index(op.f('ix_leads_lead_code'), 'leads', ['lead_code'], unique=True)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('quotations',
    sa.Column('quotation_code', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('enquiry_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('tour_name', sa.String(length=255), nullable=False),
    sa.Column('travel_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'VIEWED', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CANCELLED', name='quotation_status'), nullable=False),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('important_notes', sa.Text(), nullable=True),
    sa.Column('inclusion', sa.Text(), nullable=True),
    sa.Column('exclusion', sa.Text(), nullable=True),
    sa.Column('created_by_account_id', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_amount >= 0', name='ck_quotation_discount_non_negative'),
    sa.CheckConstraint('subtotal >= 0', name='ck_quotation_subtotal_non_negative'),
    sa.CheckConstraint('tax_amount >= 0', name='ck_quotation_tax_non_negative'),
    sa.CheckConstraint('total_amount >= 0', name='ck_quotation_total_non_negative'),
    sa.CheckConstraint('version > 0', name='ck_quotation_version_positive'),
    sa.ForeignKeyConstraint(['created_by_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['package_id'], ['tour_packages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['tour_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enquiry_id', 'version', name='uq_quotation_enquiry_version')
    )
    op.create_index(op.f('ix_quotations_customer_id'), 'quotations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_quotations_destination_id'), 'quotations', ['destination_id'], unique=False)
    op.create_index(op.f('ix_quotations_enquiry_id'), 'quotations', ['enquiry_id'], unique=False)
    op.create_index(op.f('ix_quotations_package_id'), 'quotations', ['package_id'], unique=False)
    op.create_index(op.f('ix_quotations_quotation_code'), 'quotations', ['quotation_code'], unique=True)
    op.create_index(op.f('ix_quotations_variant_id'), 'quotations', ['variant_id'], unique=False)
    op.create_table('bookings',
    sa.Column('booking_code', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('enquiry_id', sa.UUID(), nullable=True),
    sa.Column('package_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('booking_type', sa.Enum('DOMESTIC', 'INTERNATIONAL', name='tour_type'), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=True),
    sa.Column('offer_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('APP', 'WEBSITE', 'WHATSAPP', 'FACEBOOK', 'INSTAGRAM', 'PHONE', 'WALK_IN', 'EXISTING_CUSTOMER', 'REFERRAL', 'B2B', 'OFFLINE', 'OTHER', name='booking_source'), nullable=False),
    sa.Column('sales_account_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('TENTATIVE', 'CONFIRMED', 'PARTIALLY_PAID', 'FULLY_PAID', 'TRAVELLED', 'COMPLETED', 'ON_HOLD', 'CANCELLED', 'REFUNDED', name='booking_status'), nullable=False),
    sa.Column('departure_id', sa.UUID(), nullable=True),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('departure_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('adult_count', sa.Integer(), nullable=False),
    sa.Column('child_count', sa.Integer(), nullable=False),
    sa.Column('senior_count', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['departure_id'], ['tour_departures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offer_id'], ['tour_offers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['package_id'], ['tour_packages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['tour_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_code'), 'bookings', ['booking_code'], unique=True)
    op.create_index(op.f('ix_bookings_created_by'), 'bookings', ['created_by'], unique=False)
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_departure_id'), 'bookings', ['departure_id'], unique=False)
    op.create_index(op.f('ix_bookings_destination_id'), 'bookings', ['destination_id'], unique=False)
    op.create_index(op.f('ix_bookings_enquiry_id'), 'bookings', ['enquiry_id'], unique=False)
    op.create_index(op.f('ix_bookings_offer_id'), 'bookings', ['offer_id'], unique=False)
    op.create_index(op.f('ix_bookings_quotation_id'), 'bookings', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_bookings_sales_account_id'), 'bookings', ['sales_account_id'], unique=False)
    op.create_index(op.f('ix_bookings_source'), 'bookings', ['source'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('lead_activities',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('WHATSAPP', 'PHONE', 'EMAIL', 'OFFLINE', name='lead_channel'), nullable=False),
    sa.Column('activity_type', sa.Enum('CALL', 'WHATSAPP', 'EMAIL', 'NOTE', 'FOLLOW_UP', 'CUSTOMER_REQUEST', 'QUOTE_SENT', 'QUOTE_UPDATED', 'STATUS_CHANGED', 'BOOKING_CREATED', name='lead_activity_type'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_activities_lead_id'), 'lead_activities', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_activities_next_follow_up_at'), 'lead_activities', ['next_follow_up_at'], unique=False)
    op.create_table('booking_status_history',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.Enum('TENTATIVE', 'CONFIRMED', 'PARTIALLY_PAID', 'FULLY_PAID', 'TRAVELLED', 'COMPLETED', 'ON_HOLD', 'CANCELLED', 'REFUNDED', name='booking_status'), nullable=True),
    sa.Column('new_status', sa.Enum('TENTATIVE', 'CONFIRMED', 'PARTIALLY_PAID', 'FULLY_PAID', 'TRAVELLED', 'COMPLETED', 'ON_HOLD', 'CANCELLED', 'REFUNDED', name='booking_status'), nullable=False),
    sa.Column('changed_by_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_status_history_booking_id'), 'booking_status_history', ['booking_id'], unique=False)
    op.create_table('booking_travelers',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('relationship_to_customer', sa.String(length=30), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_travelers_booking_id'), 'booking_travelers', ['booking_id'], unique=False)
    op.create_table('financial_transactions',
    sa.Column('transaction_code', sa.String(length=40), nullable=False),
    sa.Column('transaction_type', sa.Enum('INCOME', 'EXPENSE', name='financial_transaction_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'FAILED', 'CANCELLED', 'REVERSED', name='financial_transaction_status'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('quotation_id', sa.UUID(), nullable=True),
    sa.Column('enquiry_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.Enum('WALLET', 'RAZORPAY', 'UPI', 'CASH', 'BANK_TRANSFER', 'NET_BANKING', 'CARD', 'OFFLINE', 'OTHER', name='payment_method'), nullable=True),
    sa.Column('category', sa.Enum('REFERRAL_INCOME', 'BOOKING_PAYMENT', 'BOOKING_REFUND', 'WALLET_CREDIT', 'WALLET_DEBIT', 'VENDOR_PAYMENT', 'TRANSFER', 'ADJUSTMENT', 'REFERRAL_REWARD', name='financial_transaction_category'), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('gateway', sa.String(length=50), nullable=True),
    sa.Column('gateway_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_account_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_financial_transactions_amount_positive'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_reference'),
    sa.UniqueConstraint('transaction_code')
    )
    op.create_index(op.f('ix_financial_transactions_booking_id'), 'financial_transactions', ['booking_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_category'), 'financial_transactions', ['category'], unique=False)
    op.create_index(op.f('ix_financial_transactions_customer_id'), 'financial_transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_enquiry_id'), 'financial_transactions', ['enquiry_id'], unique=False)
    op.create_index('ix_financial_transactions_external_reference', 'financial_transactions', ['external_reference'], unique=False)
    op.create_index(op.f('ix_financial_transactions_quotation_id'), 'financial_transactions', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_status'), 'financial_transactions', ['status'], unique=False)
    op.create_index('ix_financial_transactions_transaction_date', 'financial_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_financial_transactions_transaction_type'), 'financial_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_financial_transactions_vendor_id'), 'financial_transactions', ['vendor_id'], unique=False)
    op.create_table('tour_offer_usages',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('quotation_id', sa.UUID(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['offer_id'], ['tour_offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_offer_usages_booking_id'), 'tour_offer_usages', ['booking_id'], unique=False)
    op.create_index(op.f('ix_tour_offer_usages_customer_id'), 'tour_offer_usages', ['customer_id'], unique=False)
    op.create_index(op.f('ix_tour_offer_usages_offer_id'), 'tour_offer_usages', ['offer_id'], unique=False)
    op.create_index(op.f('ix_tour_offer_usages_quotation_id'), 'tour_offer_usages', ['quotation_id'], unique=False)
    op.create_table('trip_items',
    sa.Column('quotation_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('item_type', sa.Enum('TRANSPORT', 'FLIGHT', 'TRAIN', 'ACTIVITY', 'GUIDE', 'PERMIT', 'TRANSFER', 'OTHER', name='cost_item_type'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(quotation_id IS NOT NULL) <> (booking_id IS NOT NULL)', name='ck_trip_item_single_owner'),
    sa.CheckConstraint('quantity > 0', name='ck_trip_item_quantity_positive'),
    sa.CheckConstraint('total_price >= 0', name='ck_trip_item_total_price_non_negative'),
    sa.CheckConstraint('unit_price >= 0', name='ck_trip_item_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_items_booking_id'), 'trip_items', ['booking_id'], unique=False)
    op.create_index(op.f('ix_trip_items_item_type'), 'trip_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_trip_items_quotation_id'), 'trip_items', ['quotation_id'], unique=False)
    op.create_table('trip_itinerary',
    sa.Column('quotation_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('overnight_location', sa.String(length=255), nullable=True),
    sa.Column('meal_plan', sa.Enum('ANY', 'NONE', 'CP', 'MAP', 'AP', name='meal_plan'), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(quotation_id IS NOT NULL) <> (booking_id IS NOT NULL)', name='ck_trip_itinerary_single_owner'),
    sa.CheckConstraint('day_number > 0', name='ck_trip_itinerary_day_positive'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'day_number', name='uq_booking_itinerary_day'),
    sa.UniqueConstraint('quotation_id', 'day_number', name='uq_quotation_itinerary_day')
    )
    op.create_index(op.f('ix_trip_itinerary_booking_id'), 'trip_itinerary', ['booking_id'], unique=False)
    op.create_index(op.f('ix_trip_itinerary_quotation_id'), 'trip_itinerary', ['quotation_id'], unique=False)
    op.create_table('financial_transaction_entries',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT (debit > 0 AND credit > 0)', name='ck_financial_entry_debit_or_credit'),
    sa.CheckConstraint('credit >= 0', name='ck_financial_entry_credit_nonnegative'),
    sa.CheckConstraint('debit > 0 OR credit > 0', name='ck_financial_entry_nonzero'),
    sa.CheckConstraint('debit >= 0', name='ck_financial_entry_debit_nonnegative'),
    sa.ForeignKeyConstraint(['account_id'], ['financial_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['financial_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_transaction_entries_account_id'), 'financial_transaction_entries', ['account_id'], unique=False)
    op.create_index(op.f('ix_financial_transaction_entries_transaction_id'), 'financial_transaction_entries', ['transaction_id'], unique=False)
    op.create_table('trip_hotels',
    sa.Column('trip_item_id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=True),
    sa.Column('hotel_name', sa.String(length=255), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('room_count', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.Enum('SINGLE', 'DOUBLE', 'TWIN', 'TRIPLE', 'FAMILY', 'SUITE', 'DELUXE', 'EXECUTIVE', 'PRESIDENTIAL', name='room_type'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('check_out > check_in', name='ck_trip_hotel_checkout_after_checkin'),
    sa.CheckConstraint('nights > 0', name='ck_trip_hotel_nights_positive'),
    sa.CheckConstraint('room_count > 0', name='ck_trip_hotel_room_count_positive'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_item_id'], ['trip_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_hotels_hotel_id'), 'trip_hotels', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_trip_hotels_trip_item_id'), 'trip_hotels', ['trip_item_id'], unique=True)
    op.create_table('trip_vehicles',
    sa.Column('trip_item_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_name', sa.String(length=255), nullable=False),
    sa.Column('vehicle_type', sa.Enum('ANY', 'NONE', 'FOUR_SEATER', 'SIX_SEATER', 'TEMPO', name='vehicle_type'), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rental_minutes', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date > start_date', name='ck_trip_vehicle_end_after_start'),
    sa.CheckConstraint('quantity > 0', name='ck_trip_vehicle_quantity_positive'),
    sa.CheckConstraint('rental_minutes > 0', name='ck_trip_vehicle_rental_minutes_positive'),
    sa.ForeignKeyConstraint(['trip_item_id'], ['trip_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_vehicles_trip_item_id'), 'trip_vehicles', ['trip_item_id'], unique=True)
    op.create_index(op.f('ix_trip_vehicles_vehicle_id'), 'trip_vehicles', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_vehicles_vehicle_id'), table_name='trip_vehicles')
    op.drop_index(op.f('ix_trip_vehicles_trip_item_id'), table_name='trip_vehicles')
    op.drop_table('trip_vehicles')
    op.drop_index(op.f('ix_trip_hotels_trip_item_id'), table_name='trip_hotels')
    op.drop_index(op.f('ix_trip_hotels_hotel_id'), table_name='trip_hotels')
    op.drop_table('trip_hotels')
    op.drop_index(op.f('ix_financial_transaction_entries_transaction_id'), table_name='financial_transaction_entries')
    op.drop_index(op.f('ix_financial_transaction_entries_account_id'), table_name='financial_transaction_entries')
    op.drop_table('financial_transaction_entries')
    op.drop_index(op.f('ix_trip_itinerary_quotation_id'), table_name='trip_itinerary')
    op.drop_index(op.f('ix_trip_itinerary_booking_id'), table_name='trip_itinerary')
    op.drop_table('trip_itinerary')
    op.drop_index(op.f('ix_trip_items_quotation_id'), table_name='trip_items')
    op.drop_index(op.f('ix_trip_items_item_type'), table_name='trip_items')
    op.drop_index(op.f('ix_trip_items_booking_id'), table_name='trip_items')
    op.drop_table('trip_items')
    op.drop_index(op.f('ix_tour_offer_usages_quotation_id'), table_name='tour_offer_usages')
    op.drop_index(op.f('ix_tour_offer_usages_offer_id'), table_name='tour_offer_usages')
    op.drop_index(op.f('ix_tour_offer_usages_customer_id'), table_name='tour_offer_usages')
    op.drop_index(op.f('ix_tour_offer_usages_booking_id'), table_name='tour_offer_usages')
    op.drop_table('tour_offer_usages')
    op.drop_index(op.f('ix_financial_transactions_vendor_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_transaction_type'), table_name='financial_transactions')
    op.drop_index('ix_financial_transactions_transaction_date', table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_status'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_quotation_id'), table_name='financial_transactions')
    op.drop_index('ix_financial_transactions_external_reference', table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_enquiry_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_customer_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_category'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_booking_id'), table_name='financial_transactions')
    op.drop_table('financial_transactions')
    op.drop_index(op.f('ix_booking_travelers_booking_id'), table_name='booking_travelers')
    op.drop_table('booking_travelers')
    op.drop_index(op.f('ix_booking_status_history_booking_id'), table_name='booking_status_history')
    op.drop_table('booking_status_history')
    op.drop_index(op.f('ix_lead_activities_next_follow_up_at'), table_name='lead_activities')
    op.drop_index(op.f('ix_lead_activities_lead_id'), table_name='lead_activities')
    op.drop_table('lead_activities')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_source'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_sales_account_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_quotation_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_offer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_enquiry_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_destination_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_departure_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_created_by'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_code'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_quotations_variant_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_quotation_code'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_package_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_enquiry_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_destination_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_customer_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_code'), table_name='leads')
    op.drop_index(op.f('ix_leads_enquiry_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_account_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_visitor_events_visitor_id'), table_name='visitor_events')
    op.drop_index(op.f('ix_visitor_events_session_id'), table_name='visitor_events')
    op.drop_index(op.f('ix_visitor_events_event_name'), table_name='visitor_events')
    op.drop_table('visitor_events')
    op.drop_index(op.f('ix_tour_offer_packages_variant_id'), table_name='tour_offer_packages')
    op.drop_index(op.f('ix_tour_offer_packages_offer_id'), table_name='tour_offer_packages')
    op.drop_table('tour_offer_packages')
    op.drop_index(op.f('ix_tour_details_variant_id'), table_name='tour_details')
    op.drop_table('tour_details')
    op.drop_index(op.f('ix_tour_departures_variant_id'), table_name='tour_departures')
    op.drop_index(op.f('ix_tour_departures_departure_date'), table_name='tour_departures')
    op.drop_table('tour_departures')
    op.drop_index(op.f('ix_enquiries_visitor_id'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_vehicle_id'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_variant_id'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_status'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_package_id'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_hotel_id'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_enquiry_code'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_enquirer_email'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_destination_id'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_customer_id'), table_name='enquiries')
    op.drop_table('enquiries')
    op.drop_index(op.f('ix_visitor_sessions_visitor_id'), table_name='visitor_sessions')
    op.drop_table('visitor_sessions')
    op.drop_index(op.f('ix_tour_wishlists_package_id'), table_name='tour_wishlists')
    op.drop_index(op.f('ix_tour_wishlists_customer_id'), table_name='tour_wishlists')
    op.drop_table('tour_wishlists')
    op.drop_index('uq_tour_variants_single_default_per_package', table_name='tour_variants', postgresql_where=sa.text('is_default = true'), sqlite_where=sa.text('is_default = 1'))
    op.drop_index(op.f('ix_tour_variants_slug'), table_name='tour_variants')
    op.drop_index(op.f('ix_tour_variants_package_id'), table_name='tour_variants')
    op.drop_table('tour_variants')
    op.drop_index(op.f('ix_reviews_package_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_customer_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_referral_reward_history_referral_id'), table_name='referral_reward_history')
    op.drop_index(op.f('ix_referral_reward_history_approved_by_account_id'), table_name='referral_reward_history')
    op.drop_table('referral_reward_history')
    op.drop_index(op.f('ix_otp_challenges_visitor_id'), table_name='otp_challenges')
    op.drop_index(op.f('ix_otp_challenges_identifier'), table_name='otp_challenges')
    op.drop_index(op.f('ix_otp_challenges_customer_id'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_index(op.f('ix_visitors_visitor_code'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_fingerprint'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_customer_id'), table_name='visitors')
    op.drop_table('visitors')
    op.drop_index(op.f('ix_tour_packages_tour_code'), table_name='tour_packages')
    op.drop_index(op.f('ix_tour_packages_slug'), table_name='tour_packages')
    op.drop_index(op.f('ix_tour_packages_destination_id'), table_name='tour_packages')
    op.drop_table('tour_packages')
    op.drop_index(op.f('ix_referrals_status'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referrer_customer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_customer_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_referral_reward_configs_updated_by_account_id'), table_name='referral_reward_configs')
    op.drop_table('referral_reward_configs')
    op.drop_index(op.f('ix_notification_campaigns_recipient_id'), table_name='notification_campaigns')
    op.drop_index(op.f('ix_notification_campaigns_notification_id'), table_name='notification_campaigns')
    op.drop_index(op.f('ix_notification_campaigns_is_read'), table_name='notification_campaigns')
    op.drop_index(op.f('ix_notification_campaigns_is_delivered'), table_name='notification_campaigns')
    op.drop_table('notification_campaigns')
    op.drop_index(op.f('ix_hotels_destination_id'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_category'), table_name='hotels')
    op.drop_table('hotels')
    op.drop_index(op.f('ix_documents_uploaded_by_account_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_deleted_by_account_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_customer_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_customer_profiles_referral_code'), table_name='customer_profiles')
    op.drop_table('customer_profiles')
    op.drop_index(op.f('ix_auth_sessions_refresh_token_hash'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_account_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_table('audit_logs')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_vehicles_vehicle_type'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_table('tour_offers')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_expires_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_financial_accounts_owner_type'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_account_type'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_account_code'), table_name='financial_accounts')
    op.drop_table('financial_accounts')
    op.drop_index(op.f('ix_destinations_slug'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_name'), table_name='destinations')
    op.drop_table('destinations')
    op.drop_index('uq_staff_mobile', table_name='accounts', postgresql_where=sa.text("role = 'STAFF'"), sqlite_where=sa.text("role = 'STAFF'"))
    op.drop_index('uq_staff_email', table_name='accounts', postgresql_where=sa.text("role = 'STAFF'"), sqlite_where=sa.text("role = 'STAFF'"))
    op.drop_index('uq_admin_mobile', table_name='accounts', postgresql_where=sa.text("role = 'ADMIN'"), sqlite_where=sa.text("role = 'ADMIN'"))
    op.drop_index('uq_admin_email', table_name='accounts', postgresql_where=sa.text("role = 'ADMIN'"), sqlite_where=sa.text("role = 'ADMIN'"))
    op.drop_index('uq_active_customer_mobile', table_name='accounts', postgresql_where=sa.text("role = 'CUSTOMER' AND is_active = true"), sqlite_where=sa.text("role = 'CUSTOMER' AND is_active = true"))
    op.drop_index('uq_active_customer_email', table_name='accounts', postgresql_where=sa.text("role = 'CUSTOMER' AND is_active = true"), sqlite_where=sa.text("role = 'CUSTOMER' AND is_active = true"))
    op.drop_index(op.f('ix_accounts_role'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_mobile'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_code'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
