"""Initial schema

Revision ID: 8b0822952a14
Revises: 
Create Date: 2026-08-14 17:14:10.622786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b0822952a14'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_code', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_opt_in', sa.Boolean(), nullable=False),
    sa.Column('lead_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_lead_code'), 'leads', ['lead_code'], unique=True)
    op.create_index(op.f('ix_leads_mobile'), 'leads', ['mobile'], unique=True)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_code', sa.String(length=20), nullable=True),
    sa.Column('room_number', sa.String(length=20), nullable=True),
    sa.Column('room_type', sa.String(length=50), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('price_per_night', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_number')
    )
    op.create_index(op.f('ix_rooms_room_code'), 'rooms', ['room_code'], unique=True)
    op.create_table('tour_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tour_code', sa.String(length=20), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('destination', sa.String(length=150), nullable=False),
    sa.Column('type', sa.Enum('DOMESTIC', 'INTERNATIONAL', name='tourtype', native_enum=False, length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_packages_destination'), 'tour_packages', ['destination'], unique=False)
    op.create_index(op.f('ix_tour_packages_slug'), 'tour_packages', ['slug'], unique=True)
    op.create_index(op.f('ix_tour_packages_tour_code'), 'tour_packages', ['tour_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    op.create_index(op.f('ix_users_user_code'), 'users', ['user_code'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('price_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index(op.f('ix_vehicles_vehicle_code'), 'vehicles', ['vehicle_code'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_code', sa.String(length=20), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_mobile', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_code'), 'customers', ['customer_code'], unique=True)
    op.create_index(op.f('ix_customers_lead_id'), 'customers', ['lead_id'], unique=True)
    op.create_table('tour_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('variant_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('season_name', sa.String(length=100), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('duration_nights', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['tour_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_variants_package_id'), 'tour_variants', ['package_id'], unique=False)
    op.create_index(op.f('ix_tour_variants_variant_code'), 'tour_variants', ['variant_code'], unique=True)
    op.create_table('visitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visitor_code', sa.String(length=20), nullable=False),
    sa.Column('fingerprint', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitors_fingerprint'), 'visitors', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_visitors_lead_id'), 'visitors', ['lead_id'], unique=False)
    op.create_index(op.f('ix_visitors_visitor_code'), 'visitors', ['visitor_code'], unique=True)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_code', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('booking_type', sa.Enum('TOUR_PACKAGE', 'CUSTOM_TOUR', 'ROOM_BOOKING', name='booking_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='booking_status'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_code'), 'bookings', ['booking_code'], unique=True)
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_table('custom_tour_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_code', sa.String(length=20), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('destination', sa.String(length=150), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=True),
    sa.Column('travel_duration', sa.String(length=50), nullable=True),
    sa.Column('pax_no', sa.Integer(), nullable=False),
    sa.Column('no_room', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('meal_plan', sa.String(length=50), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_tour_requests_request_code'), 'custom_tour_requests', ['request_code'], unique=True)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_code', sa.String(length=20), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_reviews_rating'),
    sa.ForeignKeyConstraint(['package_id'], ['tour_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_package_id'), 'reviews', ['package_id'], unique=False)
    op.create_index(op.f('ix_reviews_review_code'), 'reviews', ['review_code'], unique=True)
    op.create_index(op.f('ix_reviews_visitor_id'), 'reviews', ['visitor_id'], unique=False)
    op.create_table('tour_details',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('tour_detail_code', sa.String(length=20), nullable=False),
    sa.Column('banner', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gallery', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inclusions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exclusions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('departures_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('itinerary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('route_stops', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['tour_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variant_id')
    )
    op.create_index(op.f('ix_tour_details_tour_detail_code'), 'tour_details', ['tour_detail_code'], unique=True)
    op.create_table('visitor_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_code', sa.String(length=20), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=False),
    sa.Column('landing_page', sa.Text(), nullable=True),
    sa.Column('exit_page', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('utm_term', sa.String(length=100), nullable=True),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_sessions_session_code'), 'visitor_sessions', ['session_code'], unique=True)
    op.create_index(op.f('ix_visitor_sessions_visitor_id'), 'visitor_sessions', ['visitor_id'], unique=False)
    op.create_table('room_bookings',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('room_booking_code', sa.String(length=20), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_index(op.f('ix_room_bookings_room_booking_code'), 'room_bookings', ['room_booking_code'], unique=True)
    op.create_table('vehicle_bookings',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('visitor_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_code', sa.String(length=20), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('page', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['visitor_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_events_event_code'), 'visitor_events', ['event_code'], unique=True)
    op.create_index(op.f('ix_visitor_events_event_name'), 'visitor_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_visitor_events_session_id'), 'visitor_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_visitor_events_visitor_id'), 'visitor_events', ['visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitor_events_visitor_id'), table_name='visitor_events')
    op.drop_index(op.f('ix_visitor_events_session_id'), table_name='visitor_events')
    op.drop_index(op.f('ix_visitor_events_event_name'), table_name='visitor_events')
    op.drop_index(op.f('ix_visitor_events_event_code'), table_name='visitor_events')
    op.drop_table('visitor_events')
    op.drop_table('vehicle_bookings')
    op.drop_index(op.f('ix_room_bookings_room_booking_code'), table_name='room_bookings')
    op.drop_table('room_bookings')
    op.drop_index(op.f('ix_visitor_sessions_visitor_id'), table_name='visitor_sessions')
    op.drop_index(op.f('ix_visitor_sessions_session_code'), table_name='visitor_sessions')
    op.drop_table('visitor_sessions')
    op.drop_index(op.f('ix_tour_details_tour_detail_code'), table_name='tour_details')
    op.drop_table('tour_details')
    op.drop_index(op.f('ix_reviews_visitor_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_review_code'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_package_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_custom_tour_requests_request_code'), table_name='custom_tour_requests')
    op.drop_table('custom_tour_requests')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_code'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_visitors_visitor_code'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_lead_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_fingerprint'), table_name='visitors')
    op.drop_table('visitors')
    op.drop_index(op.f('ix_tour_variants_variant_code'), table_name='tour_variants')
    op.drop_index(op.f('ix_tour_variants_package_id'), table_name='tour_variants')
    op.drop_table('tour_variants')
    op.drop_index(op.f('ix_customers_lead_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_code'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_vehicles_vehicle_code'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_user_code'), table_name='users')
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tour_packages_tour_code'), table_name='tour_packages')
    op.drop_index(op.f('ix_tour_packages_slug'), table_name='tour_packages')
    op.drop_index(op.f('ix_tour_packages_destination'), table_name='tour_packages')
    op.drop_table('tour_packages')
    op.drop_index(op.f('ix_rooms_room_code'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_mobile'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_code'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
