"""add lead lifecycle fields

Revision ID: 931eb5ce3f0a
Revises: 85f3f4c81ff7
Create Date: 2026-09-18 22:06:37.484137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931eb5ce3f0a'
down_revision: Union[str, Sequence[str], None] = '85f3f4c81ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('qualified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('lost_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('lost_reason', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('lost_reason_notes', sa.String(length=1000), nullable=True))
    op.add_column('leads', sa.Column('qualification_notes', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'qualification_notes')
    op.drop_column('leads', 'lost_reason_notes')
    op.drop_column('leads', 'lost_reason')
    op.drop_column('leads', 'lost_at')
    op.drop_column('leads', 'converted_at')
    op.drop_column('leads', 'qualified_at')
    # ### end Alembic commands ###
