"""create travel models

Revision ID: a0d5c38c7192
Revises: 331314bca490
Create Date: 2026-08-13 22:41:13.629936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0d5c38c7192'
down_revision: Union[str, Sequence[str], None] = '331314bca490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_visitor_id'), table_name='leads')
    op.drop_constraint(op.f('leads_visitor_id_fkey'), 'leads', type_='foreignkey')
    op.drop_column('leads', 'visitor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('visitor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('leads_visitor_id_fkey'), 'leads', 'visitors', ['visitor_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_leads_visitor_id'), 'leads', ['visitor_id'], unique=True)
    # ### end Alembic commands ###
