"""update travel models

Revision ID: a50c4f75b187
Revises: c57535aae0ba
Create Date: 2026-09-14 13:35:03.109638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a50c4f75b187'
down_revision: Union[str, Sequence[str], None] = 'c57535aae0ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_offers', 'is_public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_offers', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
