"""update models readable code

Revision ID: b48b3f038186
Revises: 33da5cfef073
Create Date: 2026-08-22 01:18:19.891021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48b3f038186'
down_revision: Union[str, Sequence[str], None] = '33da5cfef073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_room_code'), table_name='rooms')
    op.drop_column('rooms', 'room_code')
    op.drop_index(op.f('ix_tour_details_tour_detail_code'), table_name='tour_details')
    op.drop_column('tour_details', 'tour_detail_code')
    op.add_column('tour_variants', sa.Column('slug', sa.String(length=30), nullable=False))
    op.drop_index(op.f('ix_tour_variants_variant_code'), table_name='tour_variants')
    op.create_index(op.f('ix_tour_variants_slug'), 'tour_variants', ['slug'], unique=True)
    op.drop_column('tour_variants', 'variant_code')
    op.drop_index(op.f('ix_vehicles_vehicle_code'), table_name='vehicles')
    op.drop_column('vehicles', 'vehicle_code')
    op.drop_index(op.f('ix_visitor_events_event_code'), table_name='visitor_events')
    op.drop_column('visitor_events', 'event_code')
    op.drop_index(op.f('ix_visitor_sessions_session_code'), table_name='visitor_sessions')
    op.drop_column('visitor_sessions', 'session_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitor_sessions', sa.Column('session_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_visitor_sessions_session_code'), 'visitor_sessions', ['session_code'], unique=True)
    op.add_column('visitor_events', sa.Column('event_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_visitor_events_event_code'), 'visitor_events', ['event_code'], unique=True)
    op.add_column('vehicles', sa.Column('vehicle_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_vehicles_vehicle_code'), 'vehicles', ['vehicle_code'], unique=True)
    op.add_column('tour_variants', sa.Column('variant_code', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tour_variants_slug'), table_name='tour_variants')
    op.create_index(op.f('ix_tour_variants_variant_code'), 'tour_variants', ['variant_code'], unique=True)
    op.drop_column('tour_variants', 'slug')
    op.add_column('tour_details', sa.Column('tour_detail_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_tour_details_tour_detail_code'), 'tour_details', ['tour_detail_code'], unique=True)
    op.add_column('rooms', sa.Column('room_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_rooms_room_code'), 'rooms', ['room_code'], unique=True)
    # ### end Alembic commands ###
