"""create travel models

Revision ID: b6e8231d744e
Revises: ebb261d3a3f7
Create Date: 2026-08-15 23:49:05.054096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e8231d744e'
down_revision: Union[str, Sequence[str], None] = 'ebb261d3a3f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_enquiry_id'), table_name='leads')
    op.create_index(op.f('ix_leads_enquiry_id'), 'leads', ['enquiry_id'], unique=True)
    op.drop_constraint(op.f('leads_enquiry_id_fkey'), 'leads', type_='foreignkey')
    op.create_foreign_key(None, 'leads', 'enquiries', ['enquiry_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.create_foreign_key(op.f('leads_enquiry_id_fkey'), 'leads', 'enquiries', ['enquiry_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_leads_enquiry_id'), table_name='leads')
    op.create_index(op.f('ix_leads_enquiry_id'), 'leads', ['enquiry_id'], unique=False)
    # ### end Alembic commands ###
