"""Add Notification model

Revision ID: b74cb00a74f7
Revises: f7a8b9c0d1e2
Create Date: 2026-08-27 19:44:03.647597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74cb00a74f7'
down_revision: Union[str, Sequence[str], None] = 'f7a8b9c0d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_notification_one_recipient'), 'notifications', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('ck_notification_one_recipient'), 'notifications', '(customer_id IS NOT NULL) <> (user_id IS NOT NULL)')
    # ### end Alembic commands ###
