"""remove is_imported from customer model

Revision ID: c1a79ae7cf3d
Revises: c2d3e4f5a6b7
Create Date: 2026-09-10 00:18:48.063229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a79ae7cf3d'
down_revision: Union[str, Sequence[str], None] = 'c2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_profiles', 'is_imported')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_profiles', sa.Column('is_imported', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
