"""Fix the destinaton fks in models

Revision ID: d4949001d30f
Revises: c1a79ae7cf3d
Create Date: 2026-09-10 14:07:54.943108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4949001d30f'
down_revision: Union[str, Sequence[str], None] = 'c1a79ae7cf3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('destination_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_enquiries_destination_id'), 'enquiries', ['destination_id'], unique=False)
    op.create_foreign_key(None, 'enquiries', 'destinations', ['destination_id'], ['id'], ondelete='SET NULL')
    op.add_column('hotels', sa.Column('destination_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_hotels_destination_id'), 'hotels', ['destination_id'], unique=False)
    op.create_foreign_key(None, 'hotels', 'destinations', ['destination_id'], ['id'], ondelete='SET NULL')
    op.add_column('quotations', sa.Column('destination_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_quotations_destination_id'), 'quotations', ['destination_id'], unique=False)
    op.create_foreign_key(None, 'quotations', 'destinations', ['destination_id'], ['id'], ondelete='SET NULL')
    op.add_column('tour_packages', sa.Column('destination_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_tour_packages_destination'), table_name='tour_packages')
    op.create_index(op.f('ix_tour_packages_destination_id'), 'tour_packages', ['destination_id'], unique=False)
    op.create_foreign_key(None, 'tour_packages', 'destinations', ['destination_id'], ['id'], ondelete='SET NULL')
    op.drop_column('tour_packages', 'destination')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_packages', sa.Column('destination', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tour_packages', type_='foreignkey')
    op.drop_index(op.f('ix_tour_packages_destination_id'), table_name='tour_packages')
    op.create_index(op.f('ix_tour_packages_destination'), 'tour_packages', ['destination'], unique=False)
    op.drop_column('tour_packages', 'destination_id')
    op.drop_constraint(None, 'quotations', type_='foreignkey')
    op.drop_index(op.f('ix_quotations_destination_id'), table_name='quotations')
    op.drop_column('quotations', 'destination_id')
    op.drop_constraint(None, 'hotels', type_='foreignkey')
    op.drop_index(op.f('ix_hotels_destination_id'), table_name='hotels')
    op.drop_column('hotels', 'destination_id')
    op.drop_constraint(None, 'enquiries', type_='foreignkey')
    op.drop_index(op.f('ix_enquiries_destination_id'), table_name='enquiries')
    op.drop_column('enquiries', 'destination_id')
    # ### end Alembic commands ###
