"""remove is_popular from destination model

Revision ID: d8d3b3b40f84
Revises: d4949001d30f
Create Date: 2026-09-10 16:45:21.179626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8d3b3b40f84'
down_revision: Union[str, Sequence[str], None] = 'd4949001d30f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destinations', 'is_popular')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('is_popular', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
