"""add TourWishlist model

Revision ID: df13c404c735
Revises: 5e6f7a8b9c0d
Create Date: 2026-08-25 23:44:21.866162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df13c404c735'
down_revision: Union[str, Sequence[str], None] = '5e6f7a8b9c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_wishlists',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['tour_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'package_id', name='uq_tour_wishlist_customer_package')
    )
    op.create_index(op.f('ix_tour_wishlists_customer_id'), 'tour_wishlists', ['customer_id'], unique=False)
    op.create_index(op.f('ix_tour_wishlists_package_id'), 'tour_wishlists', ['package_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tour_wishlists_package_id'), table_name='tour_wishlists')
    op.drop_index(op.f('ix_tour_wishlists_customer_id'), table_name='tour_wishlists')
    op.drop_table('tour_wishlists')
    # ### end Alembic commands ###
