"""Add created_at @ wishlist  model

Revision ID: e0dfa52ae7d1
Revises: b74cb00a74f7
Create Date: 2026-08-27 19:51:41.213251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0dfa52ae7d1'
down_revision: Union[str, Sequence[str], None] = 'b74cb00a74f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_wishlists', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_wishlists', 'created_at')
    # ### end Alembic commands ###
