"""add review_gallery field @review model

Revision ID: e8c99ed1ab5f
Revises: 2d3d203ea6b0
Create Date: 2026-08-19 21:02:20.520347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8c99ed1ab5f'
down_revision: Union[str, Sequence[str], None] = '2d3d203ea6b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review_gallery', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'review_gallery')
    # ### end Alembic commands ###
