"""create travel models

Revision ID: ebb261d3a3f7
Revises: 777ddcf11128
Create Date: 2026-08-15 23:12:58.783964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebb261d3a3f7'
down_revision: Union[str, Sequence[str], None] = '777ddcf11128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_bookings_room_booking_code'), table_name='room_bookings')
    op.drop_table('room_bookings')
    op.drop_table('vehicle_bookings')
    op.drop_index(op.f('ix_custom_tour_requests_customer_id'), table_name='custom_tour_requests')
    op.drop_index(op.f('ix_custom_tour_requests_request_code'), table_name='custom_tour_requests')
    op.drop_index(op.f('ix_custom_tour_requests_visitor_id'), table_name='custom_tour_requests')
    op.drop_table('custom_tour_requests')
    op.drop_index(op.f('ix_bookings_booking_code'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_table('bookings')
    op.add_column('enquiries', sa.Column('room_id', sa.UUID(), nullable=True))
    op.add_column('enquiries', sa.Column('vehicle_id', sa.UUID(), nullable=True))
    op.add_column('enquiries', sa.Column('destination', sa.String(length=150), nullable=True))
    op.add_column('enquiries', sa.Column('travel_date', sa.Date(), nullable=True))
    op.add_column('enquiries', sa.Column('travel_duration', sa.String(length=50), nullable=True))
    op.add_column('enquiries', sa.Column('pax_no', sa.Integer(), nullable=True))
    op.add_column('enquiries', sa.Column('no_room', sa.Integer(), nullable=True))
    op.add_column('enquiries', sa.Column('vehicle_type', sa.String(length=50), nullable=True))
    op.add_column('enquiries', sa.Column('meal_plan', sa.String(length=50), nullable=True))
    op.add_column('enquiries', sa.Column('special_requirements', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'enquiries', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key(None, 'enquiries', 'vehicles', ['vehicle_id'], ['id'])
    op.add_column('lead_activities', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('leads', 'enquiry_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('reviews', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('rooms', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('tour_details', sa.Column('id', sa.UUID(), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('tour_details', 'id')
    op.alter_column('rooms', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('reviews', 'updated_at')
    op.alter_column('leads', 'enquiry_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('lead_activities', 'updated_at')
    op.drop_constraint(None, 'enquiries', type_='foreignkey')
    op.drop_constraint(None, 'enquiries', type_='foreignkey')
    op.drop_column('enquiries', 'special_requirements')
    op.drop_column('enquiries', 'meal_plan')
    op.drop_column('enquiries', 'vehicle_type')
    op.drop_column('enquiries', 'no_room')
    op.drop_column('enquiries', 'pax_no')
    op.drop_column('enquiries', 'travel_duration')
    op.drop_column('enquiries', 'travel_date')
    op.drop_column('enquiries', 'destination')
    op.drop_column('enquiries', 'vehicle_id')
    op.drop_column('enquiries', 'room_id')
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('booking_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('booking_type', postgresql.ENUM('TOUR_PACKAGE', 'CUSTOM_TOUR', 'ROOM_BOOKING', name='booking_type'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='booking_status'), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('bookings_customer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bookings_pkey'))
    )
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_booking_code'), 'bookings', ['booking_code'], unique=True)
    op.create_table('custom_tour_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('visitor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('mobile', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('destination', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('travel_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('travel_duration', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('pax_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('no_room', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vehicle_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('meal_plan', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('special_requirements', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('enquiry_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('custom_tour_requests_customer_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], name=op.f('custom_tour_requests_enquiry_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], name=op.f('custom_tour_requests_visitor_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('custom_tour_requests_pkey'))
    )
    op.create_index(op.f('ix_custom_tour_requests_visitor_id'), 'custom_tour_requests', ['visitor_id'], unique=False)
    op.create_index(op.f('ix_custom_tour_requests_request_code'), 'custom_tour_requests', ['request_code'], unique=True)
    op.create_index(op.f('ix_custom_tour_requests_customer_id'), 'custom_tour_requests', ['customer_id'], unique=False)
    op.create_table('vehicle_bookings',
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('adults', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('children', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('vehicle_bookings_booking_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('vehicle_bookings_vehicle_id_fkey')),
    sa.PrimaryKeyConstraint('booking_id', name=op.f('vehicle_bookings_pkey'))
    )
    op.create_table('room_bookings',
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('room_booking_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('check_in', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('check_out', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('adults', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('children', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('room_bookings_booking_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('room_bookings_room_id_fkey')),
    sa.PrimaryKeyConstraint('booking_id', name=op.f('room_bookings_pkey'))
    )
    op.create_index(op.f('ix_room_bookings_room_booking_code'), 'room_bookings', ['room_booking_code'], unique=True)
    # ### end Alembic commands ###
