"""Add new travel & CRM  models

Revision ID: f16e3fb091a7
Revises: e7b8c9d0e1f2
Create Date: 2026-09-08 22:06:01.452261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f16e3fb091a7'
down_revision: Union[str, Sequence[str], None] = 'e7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Reuse the booking_status type created by the initial schema and extend
    # it with the statuses used by the current booking models.
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'booking_status') THEN
                ALTER TYPE booking_status ADD VALUE IF NOT EXISTS 'TENTATIVE';
                ALTER TYPE booking_status ADD VALUE IF NOT EXISTS 'PARTIALLY_PAID';
                ALTER TYPE booking_status ADD VALUE IF NOT EXISTS 'FULLY_PAID';
                ALTER TYPE booking_status ADD VALUE IF NOT EXISTS 'TRAVELLED';
                ALTER TYPE booking_status ADD VALUE IF NOT EXISTS 'ON_HOLD';
                ALTER TYPE booking_status ADD VALUE IF NOT EXISTS 'REFUNDED';
            END IF;
        END
        $$;
    """)
    op.create_table('accounts',
    sa.Column('account_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', 'CUSTOMER', name='account_role'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_pic', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_code'), 'accounts', ['account_code'], unique=True)
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_index(op.f('ix_accounts_mobile'), 'accounts', ['mobile'], unique=True)
    op.create_index(op.f('ix_accounts_role'), 'accounts', ['role'], unique=False)
    op.create_table('destinations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('is_domestic', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_popular', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_name'), 'destinations', ['name'], unique=False)
    op.create_index(op.f('ix_destinations_slug'), 'destinations', ['slug'], unique=True)
    op.create_table('hotels',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tour_offers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'EXPIRED', 'DISABLED', name='offer_status'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FIXED', name='offer_discount_type'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_booking_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('per_customer_limit', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_stackable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('discount_value >= 0', name='ck_tour_offer_discount_value_non_negative'),
    sa.CheckConstraint('per_customer_limit IS NULL OR per_customer_limit > 0', name='ck_tour_offer_customer_limit_positive'),
    sa.CheckConstraint('usage_limit IS NULL OR usage_limit > 0', name='ck_tour_offer_usage_limit_positive'),
    sa.CheckConstraint('valid_until > valid_from', name='ck_tour_offer_valid_dates'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_offers_code'), 'tour_offers', ['code'], unique=True)
    op.create_table('vendors',
    sa.Column('vendor_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_vendor_code'), 'vendors', ['vendor_code'], unique=True)
    op.create_table('audit_logs',
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_profiles',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_mobile', sa.String(length=20), nullable=True),
    sa.Column('source', postgresql.ENUM('WEBSITE', 'WHATSAPP', 'PHONE', 'EMAIL', 'OFFLINE', 'IMPORT', 'REFERRAL', 'OTHER', name='lead_source', create_type=False), nullable=False),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('special_discount_type', sa.Enum('PERCENTAGE', 'FIXED', name='discount_type'), nullable=True),
    sa.Column('special_discount', sa.String(length=50), nullable=True),
    sa.Column('referral_code', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_index(op.f('ix_customer_profiles_referral_code'), 'customer_profiles', ['referral_code'], unique=True)
    op.create_table('expenses',
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expense_category', sa.String(length=100), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('attachments', sa.ARRAY(sa.String(length=1000)), nullable=True),
    sa.Column('created_by_account_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_created_by_account_id'), 'expenses', ['created_by_account_id'], unique=False)
    op.create_index(op.f('ix_expenses_expense_category'), 'expenses', ['expense_category'], unique=False)
    op.create_index(op.f('ix_expenses_payment_method'), 'expenses', ['payment_method'], unique=False)
    op.create_index(op.f('ix_expenses_vendor_id'), 'expenses', ['vendor_id'], unique=False)
    op.create_table('notification_campaigns',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('is_delivered', sa.Boolean(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_campaigns_is_delivered'), 'notification_campaigns', ['is_delivered'], unique=False)
    op.create_index(op.f('ix_notification_campaigns_is_read'), 'notification_campaigns', ['is_read'], unique=False)
    op.create_index(op.f('ix_notification_campaigns_notification_id'), 'notification_campaigns', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notification_campaigns_recipient_id'), 'notification_campaigns', ['recipient_id'], unique=False)
    op.create_table('tour_departures',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('available_seats >= 0 AND available_seats <= total_seats', name='ck_departure_available_seats_valid'),
    sa.CheckConstraint('total_seats >= 0', name='ck_departure_total_seats_non_negative'),
    sa.ForeignKeyConstraint(['variant_id'], ['tour_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_departures_departure_date'), 'tour_departures', ['departure_date'], unique=False)
    op.create_index(op.f('ix_tour_departures_variant_id'), 'tour_departures', ['variant_id'], unique=False)
    op.create_table('tour_offer_packages',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['tour_offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['tour_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_offer_packages_offer_id'), 'tour_offer_packages', ['offer_id'], unique=False)
    op.create_index(op.f('ix_tour_offer_packages_variant_id'), 'tour_offer_packages', ['variant_id'], unique=False)
    op.create_table('quotations',
    sa.Column('quotation_code', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('enquiry_id', sa.UUID(), nullable=True),
    sa.Column('package_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('tour_name', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('travel_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adult_count', sa.Integer(), nullable=False),
    sa.Column('child_count', sa.Integer(), nullable=False),
    sa.Column('senior_count', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('room_count', sa.Integer(), nullable=False),
    sa.Column('vehicle', sa.String(length=100), nullable=True),
    sa.Column('meal_plan', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'VIEWED', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CANCELLED', name='quotation_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('created_by_account_id', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('adult_count + child_count + senior_count > 0', name='ck_quotation_has_traveller'),
    sa.CheckConstraint('adult_count >= 0', name='ck_quotation_adult_count_non_negative'),
    sa.CheckConstraint('child_count >= 0', name='ck_quotation_child_count_non_negative'),
    sa.CheckConstraint('discount_amount >= 0', name='ck_quotation_discount_non_negative'),
    sa.CheckConstraint('senior_count >= 0', name='ck_quotation_senior_count_non_negative'),
    sa.CheckConstraint('subtotal >= 0', name='ck_quotation_subtotal_non_negative'),
    sa.CheckConstraint('tax_amount >= 0', name='ck_quotation_tax_non_negative'),
    sa.CheckConstraint('total_amount >= 0', name='ck_quotation_total_non_negative'),
    sa.CheckConstraint('version > 0', name='ck_quotation_version_positive'),
    sa.ForeignKeyConstraint(['created_by_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['package_id'], ['tour_packages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['tour_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enquiry_id', 'version', name='uq_quotation_enquiry_version')
    )
    op.create_index(op.f('ix_quotations_created_by_account_id'), 'quotations', ['created_by_account_id'], unique=False)
    op.create_index(op.f('ix_quotations_customer_id'), 'quotations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_quotations_enquiry_id'), 'quotations', ['enquiry_id'], unique=False)
    op.create_index(op.f('ix_quotations_package_id'), 'quotations', ['package_id'], unique=False)
    op.create_index(op.f('ix_quotations_quotation_code'), 'quotations', ['quotation_code'], unique=True)
    op.create_index(op.f('ix_quotations_status'), 'quotations', ['status'], unique=False)
    op.create_index(op.f('ix_quotations_variant_id'), 'quotations', ['variant_id'], unique=False)
    op.create_table('bookings',
    sa.Column('booking_code', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('enquiry_id', sa.UUID(), nullable=True),
    sa.Column('package_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('booking_type', sa.String(length=30), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('APP', 'WEBSITE', 'WHATSAPP', 'FACEBOOK', 'INSTAGRAM', 'PHONE', 'WALK_IN', 'EXISTING_CUSTOMER', 'REFERRAL', 'B2B', 'OFFLINE', 'OTHER', name='booking_source'), nullable=False),
    sa.Column('sales_account_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('TENTATIVE', 'CONFIRMED', 'PARTIALLY_PAID', 'FULLY_PAID', 'TRAVELLED', 'COMPLETED', 'ON_HOLD', 'CANCELLED', 'REFUNDED', name='booking_status', create_type=False), nullable=False),
    sa.Column('departure_id', sa.UUID(), nullable=True),
    sa.Column('adult_count', sa.Integer(), nullable=False),
    sa.Column('child_count', sa.Integer(), nullable=False),
    sa.Column('senior_count', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['departure_id'], ['tour_departures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['package_id'], ['tour_packages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['tour_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_code'), 'bookings', ['booking_code'], unique=True)
    op.create_index(op.f('ix_bookings_created_by'), 'bookings', ['created_by'], unique=False)
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_departure_id'), 'bookings', ['departure_id'], unique=False)
    op.create_index(op.f('ix_bookings_enquiry_id'), 'bookings', ['enquiry_id'], unique=True)
    op.create_index(op.f('ix_bookings_quotation_id'), 'bookings', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_bookings_sales_account_id'), 'bookings', ['sales_account_id'], unique=False)
    op.create_index(op.f('ix_bookings_source'), 'bookings', ['source'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('quotation_items',
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Enum('HOTEL', 'TRANSPORT', 'FLIGHT', 'TRAIN', 'MEAL', 'ACTIVITY', 'GUIDE', 'PERMIT', 'TRANSFER', 'OTHER', name='quotation_item_type'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_quotation_item_quantity_positive'),
    sa.CheckConstraint('total_price >= 0', name='ck_quotation_item_total_price_non_negative'),
    sa.CheckConstraint('unit_price >= 0', name='ck_quotation_item_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_items_item_type'), 'quotation_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_quotation_items_quotation_id'), 'quotation_items', ['quotation_id'], unique=False)
    op.create_table('booking_costs',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('cost_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('estimated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_costs_booking_id'), 'booking_costs', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_costs_vendor_id'), 'booking_costs', ['vendor_id'], unique=False)
    op.create_table('booking_payments',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('transaction_type', sa.Enum('PAYMENT', 'REFUND', name='transaction_type'), nullable=False),
    sa.Column('payment_method', sa.Enum('RAZORPAY', 'UPI', 'CASH', 'BANK_TRANSFER', 'CARD', 'OFFLINE', 'OTHER', name='payment_method'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('gateway', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_order_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_signature', sa.String(length=500), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_account_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_booking_payment_amount_positive'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_payments_booking_id'), 'booking_payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_payments_gateway_order_id'), 'booking_payments', ['gateway_order_id'], unique=False)
    op.create_index(op.f('ix_booking_payments_gateway_payment_id'), 'booking_payments', ['gateway_payment_id'], unique=True)
    op.create_index(op.f('ix_booking_payments_payment_method'), 'booking_payments', ['payment_method'], unique=False)
    op.create_index(op.f('ix_booking_payments_status'), 'booking_payments', ['status'], unique=False)
    op.create_index(op.f('ix_booking_payments_transaction_id'), 'booking_payments', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_booking_payments_transaction_type'), 'booking_payments', ['transaction_type'], unique=False)
    op.create_table('booking_status_history',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', postgresql.ENUM('TENTATIVE', 'CONFIRMED', 'PARTIALLY_PAID', 'FULLY_PAID', 'TRAVELLED', 'COMPLETED', 'ON_HOLD', 'CANCELLED', 'REFUNDED', name='booking_status', create_type=False), nullable=True),
    sa.Column('status', postgresql.ENUM('TENTATIVE', 'CONFIRMED', 'PARTIALLY_PAID', 'FULLY_PAID', 'TRAVELLED', 'COMPLETED', 'ON_HOLD', 'CANCELLED', 'REFUNDED', name='booking_status', create_type=False), nullable=False),
    sa.Column('changed_by_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_status_history_booking_id'), 'booking_status_history', ['booking_id'], unique=False)
    op.create_table('booking_travelers',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('traveler_type', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('relationship_to_customer', sa.String(length=30), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_travelers_booking_id'), 'booking_travelers', ['booking_id'], unique=False)
    op.create_table('room_allocations',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('room_number', sa.String(length=30), nullable=True),
    sa.Column('room_type', sa.String(length=50), nullable=True),
    sa.Column('occupant_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_allocations_booking_id'), 'room_allocations', ['booking_id'], unique=False)
    op.create_index(op.f('ix_room_allocations_room_id'), 'room_allocations', ['room_id'], unique=False)
    op.create_table('vehicle_allocations',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_type', sa.String(length=100), nullable=True),
    sa.Column('vehicle_name', sa.String(length=255), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('driver_name', sa.String(length=255), nullable=True),
    sa.Column('driver_mobile', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_allocations_booking_id'), 'vehicle_allocations', ['booking_id'], unique=False)
    op.create_index(op.f('ix_vehicle_allocations_vehicle_id'), 'vehicle_allocations', ['vehicle_id'], unique=False)
    op.create_table('vendor_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('cost_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['cost_id'], ['booking_costs.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_expenses',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('cost_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cost_id'], ['booking_costs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_expenses_booking_id'), 'vendor_expenses', ['booking_id'], unique=False)
    op.create_index(op.f('ix_vendor_expenses_cost_id'), 'vendor_expenses', ['cost_id'], unique=False)
    op.create_index(op.f('ix_vendor_expenses_vendor_id'), 'vendor_expenses', ['vendor_id'], unique=False)
    op.create_table('vendor_payments',
    sa.Column('booking_cost_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['booking_cost_id'], ['booking_costs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_customer_tours_created_by_user_id'), table_name='customer_tours')
    op.drop_index(op.f('ix_customer_tours_customer_id'), table_name='customer_tours')
    op.drop_index(op.f('ix_customer_tours_enquiry_id'), table_name='customer_tours')
    op.drop_index(op.f('ix_customer_tours_package_id'), table_name='customer_tours')
    op.drop_index(op.f('ix_customer_tours_status'), table_name='customer_tours')
    op.drop_index(op.f('ix_customer_tours_variant_id'), table_name='customer_tours')
    op.drop_table('customer_tours')
    op.drop_constraint(op.f('auth_sessions_user_id_fkey'), 'auth_sessions', type_='foreignkey')
    op.drop_constraint(op.f('documents_uploaded_by_user_id_fkey'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('documents_deleted_by_user_id_fkey'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('lead_activities_user_id_fkey'), 'lead_activities', type_='foreignkey')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_index(op.f('ix_users_user_code'), table_name='users')
    op.drop_table('users')
    op.drop_constraint(op.f('reviews_customer_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('enquiries_customer_id_fkey'), 'enquiries', type_='foreignkey')
    op.drop_constraint(op.f('leads_customer_id_fkey'), 'leads', type_='foreignkey')
    op.drop_constraint(op.f('visitors_customer_id_fkey'), 'visitors', type_='foreignkey')
    op.drop_constraint(op.f('otp_challenges_customer_id_fkey'), 'otp_challenges', type_='foreignkey')
    op.drop_constraint(op.f('auth_sessions_customer_id_fkey'), 'auth_sessions', type_='foreignkey')
    op.drop_constraint(op.f('tour_wishlists_customer_id_fkey'), 'tour_wishlists', type_='foreignkey')
    op.drop_constraint(op.f('documents_customer_id_fkey'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('documents_deleted_by_customer_id_fkey'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('documents_uploaded_by_customer_id_fkey'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('referrals_referred_customer_id_fkey'), 'referrals', type_='foreignkey')
    op.drop_constraint(op.f('referrals_referrer_customer_id_fkey'), 'referrals', type_='foreignkey')
    op.drop_constraint(op.f('notifications_customer_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_customers_customer_code'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_mobile'), table_name='customers')
    op.drop_index(op.f('ix_customers_referral_code'), table_name='customers')
    op.drop_table('customers')
    op.add_column('auth_sessions', sa.Column('account_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_auth_sessions_customer_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.create_index(op.f('ix_auth_sessions_account_id'), 'auth_sessions', ['account_id'], unique=False)
    op.create_foreign_key(None, 'auth_sessions', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('ck_auth_session_actor_owner'), 'auth_sessions', type_='check')
    op.drop_column('auth_sessions', 'user_id')
    op.drop_column('auth_sessions', 'actor_type')
    op.drop_column('auth_sessions', 'customer_id')
    op.add_column('documents', sa.Column('uploaded_by_account_id', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('deleted_by_account_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_documents_deleted_by_customer_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_deleted_by_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_uploaded_by_customer_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_uploaded_by_user_id'), table_name='documents')
    op.create_index(op.f('ix_documents_deleted_by_account_id'), 'documents', ['deleted_by_account_id'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by_account_id'), 'documents', ['uploaded_by_account_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'accounts', ['deleted_by_account_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'documents', 'accounts', ['uploaded_by_account_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'documents', 'accounts', ['customer_id'], ['id'], ondelete='SET NULL')
    op.drop_column('documents', 'uploaded_by_user_id')
    op.drop_column('documents', 'deleted_by_customer_id')
    op.drop_column('documents', 'uploaded_by_customer_id')
    op.drop_column('documents', 'deleted_by_user_id')
    op.add_column('enquiries', sa.Column('adult_count', sa.Integer(), nullable=True))
    op.add_column('enquiries', sa.Column('child_count', sa.Integer(), nullable=True))
    op.add_column('enquiries', sa.Column('senior_count', sa.Integer(), nullable=True))
    op.add_column('enquiries', sa.Column('room_count', sa.Integer(), nullable=True))
    op.add_column('enquiries', sa.Column('budget_min', sa.Integer(), nullable=True))
    op.add_column('enquiries', sa.Column('budget_max', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'enquiries', 'accounts', ['customer_id'], ['id'], ondelete='SET NULL')
    op.drop_column('enquiries', 'no_room')
    op.drop_column('enquiries', 'pax_no')
    op.add_column('lead_activities', sa.Column('account_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'lead_activities', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    op.drop_column('lead_activities', 'user_id')
    op.create_foreign_key(None, 'leads', 'accounts', ['customer_id'], ['id'], ondelete='SET NULL')
    op.add_column('notifications', sa.Column('recipient_ids', postgresql.ARRAY(sa.UUID()), nullable=True))
    op.drop_index(op.f('ix_notifications_customer_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'user_id')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'customer_id')
    op.create_foreign_key(None, 'otp_challenges', 'accounts', ['customer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'referrals', 'accounts', ['referred_customer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'referrals', 'accounts', ['referrer_customer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'accounts', ['customer_id'], ['id'], ondelete='SET NULL')
    op.add_column('rooms', sa.Column('hotel_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_rooms_hotel_id'), 'rooms', ['hotel_id'], unique=False)
    op.create_foreign_key(None, 'rooms', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tour_details', 'departures_dates')
    op.drop_column('tour_variants', 'availability')
    op.drop_column('tour_variants', 'seats')
    op.create_foreign_key(None, 'tour_wishlists', 'accounts', ['customer_id'], ['id'], ondelete='CASCADE')
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'vehicletype') THEN
                CREATE TYPE vehicletype AS ENUM ('ANY', 'NONE', 'FOUR_SEATER', 'SIX_SEATER', 'TEMPO');
            END IF;
        END
        $$;
    """)
    op.add_column(
        'vehicles',
        sa.Column(
            'vehicle_type',
            postgresql.ENUM(
                'ANY',
                'NONE',
                'FOUR_SEATER',
                'SIX_SEATER',
                'TEMPO',
                name='vehicletype',
                create_type=False,
            ),
            nullable=False,
        ),
    )
    op.alter_column('vehicles', 'registration_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_vehicles_vehicle_type'), 'vehicles', ['vehicle_type'], unique=False)
    op.create_foreign_key(None, 'visitors', 'accounts', ['customer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visitors', type_='foreignkey')
    op.create_foreign_key(op.f('visitors_customer_id_fkey'), 'visitors', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_vehicles_vehicle_type'), table_name='vehicles')
    op.alter_column('vehicles', 'registration_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('vehicles', 'vehicle_type')
    op.drop_constraint(None, 'tour_wishlists', type_='foreignkey')
    op.create_foreign_key(op.f('tour_wishlists_customer_id_fkey'), 'tour_wishlists', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.add_column('tour_variants', sa.Column('seats', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tour_variants', sa.Column('availability', sa.VARCHAR(length=20), server_default=sa.text("'AVAILABLE'::character varying"), autoincrement=False, nullable=True))
    op.add_column('tour_details', sa.Column('departures_dates', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_index(op.f('ix_rooms_hotel_id'), table_name='rooms')
    op.drop_column('rooms', 'hotel_id')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_customer_id_fkey'), 'reviews', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.create_foreign_key(op.f('referrals_referrer_customer_id_fkey'), 'referrals', 'customers', ['referrer_customer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('referrals_referred_customer_id_fkey'), 'referrals', 'customers', ['referred_customer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'otp_challenges', type_='foreignkey')
    op.create_foreign_key(op.f('otp_challenges_customer_id_fkey'), 'otp_challenges', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.add_column('notifications', sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('notifications_customer_id_fkey'), 'notifications', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_customer_id'), 'notifications', ['customer_id'], unique=False)
    op.drop_column('notifications', 'recipient_ids')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.create_foreign_key(op.f('leads_customer_id_fkey'), 'leads', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.add_column('lead_activities', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lead_activities', type_='foreignkey')
    op.create_foreign_key(op.f('lead_activities_user_id_fkey'), 'lead_activities', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('lead_activities', 'account_id')
    op.add_column('enquiries', sa.Column('pax_no', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('enquiries', sa.Column('no_room', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'enquiries', type_='foreignkey')
    op.create_foreign_key(op.f('enquiries_customer_id_fkey'), 'enquiries', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.drop_column('enquiries', 'budget_max')
    op.drop_column('enquiries', 'budget_min')
    op.drop_column('enquiries', 'room_count')
    op.drop_column('enquiries', 'senior_count')
    op.drop_column('enquiries', 'child_count')
    op.drop_column('enquiries', 'adult_count')
    op.add_column('documents', sa.Column('deleted_by_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('uploaded_by_customer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('deleted_by_customer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('uploaded_by_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_deleted_by_customer_id_fkey'), 'documents', 'customers', ['deleted_by_customer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('documents_deleted_by_user_id_fkey'), 'documents', 'users', ['deleted_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('documents_uploaded_by_customer_id_fkey'), 'documents', 'customers', ['uploaded_by_customer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('documents_uploaded_by_user_id_fkey'), 'documents', 'users', ['uploaded_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('documents_customer_id_fkey'), 'documents', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_documents_uploaded_by_account_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_deleted_by_account_id'), table_name='documents')
    op.create_index(op.f('ix_documents_uploaded_by_user_id'), 'documents', ['uploaded_by_user_id'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by_customer_id'), 'documents', ['uploaded_by_customer_id'], unique=False)
    op.create_index(op.f('ix_documents_deleted_by_user_id'), 'documents', ['deleted_by_user_id'], unique=False)
    op.create_index(op.f('ix_documents_deleted_by_customer_id'), 'documents', ['deleted_by_customer_id'], unique=False)
    op.drop_column('documents', 'deleted_by_account_id')
    op.drop_column('documents', 'uploaded_by_account_id')
    op.add_column('auth_sessions', sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('auth_sessions', sa.Column('actor_type', postgresql.ENUM('USER', 'CUSTOMER', 'ADMIN', 'STAFF', name='actor_type'), server_default=sa.text("'USER'::actor_type"), autoincrement=False, nullable=False))
    op.add_column('auth_sessions', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_check_constraint(op.f('ck_auth_session_actor_owner'), 'auth_sessions', "(actor_type = ANY (ARRAY['ADMIN'::actor_type, 'STAFF'::actor_type])) AND user_id IS NOT NULL AND customer_id IS NULL OR actor_type = 'CUSTOMER'::actor_type AND customer_id IS NOT NULL AND user_id IS NULL")
    op.drop_constraint(None, 'auth_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('auth_sessions_user_id_fkey'), 'auth_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('auth_sessions_customer_id_fkey'), 'auth_sessions', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_auth_sessions_account_id'), table_name='auth_sessions')
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_customer_id'), 'auth_sessions', ['customer_id'], unique=False)
    op.drop_column('auth_sessions', 'account_id')
    op.create_table('customers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('customer_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('mobile', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('emergency_contact_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('emergency_contact_mobile', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('source', postgresql.ENUM('WEBSITE', 'WHATSAPP', 'PHONE', 'EMAIL', 'OFFLINE', 'IMPORT', 'REFERRAL', 'OTHER', name='lead_source', create_type=False), autoincrement=False, nullable=False),
    sa.Column('is_imported', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('profile_pic', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('referral_code', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('customers_pkey'))
    )
    op.create_index(op.f('ix_customers_referral_code'), 'customers', ['referral_code'], unique=True)
    op.create_index(op.f('ix_customers_mobile'), 'customers', ['mobile'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_customer_code'), 'customers', ['customer_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('mobile', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'STAFF', name='user_role'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('profile_pic', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_user_code'), 'users', ['user_code'], unique=True)
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('customer_tours',
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('package_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('variant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('enquiry_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tour_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('destination', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('travel_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('return_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('pax_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PLANNED', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='customer_tour_status'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('customer_tours_created_by_user_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('customer_tours_customer_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], name=op.f('customer_tours_enquiry_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['package_id'], ['tour_packages.id'], name=op.f('customer_tours_package_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['tour_variants.id'], name=op.f('customer_tours_variant_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_tours_pkey'))
    )
    op.create_index(op.f('ix_customer_tours_variant_id'), 'customer_tours', ['variant_id'], unique=False)
    op.create_index(op.f('ix_customer_tours_status'), 'customer_tours', ['status'], unique=False)
    op.create_index(op.f('ix_customer_tours_package_id'), 'customer_tours', ['package_id'], unique=False)
    op.create_index(op.f('ix_customer_tours_enquiry_id'), 'customer_tours', ['enquiry_id'], unique=True)
    op.create_index(op.f('ix_customer_tours_customer_id'), 'customer_tours', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_tours_created_by_user_id'), 'customer_tours', ['created_by_user_id'], unique=False)
    op.drop_table('vendor_payments')
    op.drop_index(op.f('ix_vendor_expenses_vendor_id'), table_name='vendor_expenses')
    op.drop_index(op.f('ix_vendor_expenses_cost_id'), table_name='vendor_expenses')
    op.drop_index(op.f('ix_vendor_expenses_booking_id'), table_name='vendor_expenses')
    op.drop_table('vendor_expenses')
    op.drop_table('vendor_bookings')
    op.drop_index(op.f('ix_vehicle_allocations_vehicle_id'), table_name='vehicle_allocations')
    op.drop_index(op.f('ix_vehicle_allocations_booking_id'), table_name='vehicle_allocations')
    op.drop_table('vehicle_allocations')
    op.drop_index(op.f('ix_room_allocations_room_id'), table_name='room_allocations')
    op.drop_index(op.f('ix_room_allocations_booking_id'), table_name='room_allocations')
    op.drop_table('room_allocations')
    op.drop_index(op.f('ix_booking_travelers_booking_id'), table_name='booking_travelers')
    op.drop_table('booking_travelers')
    op.drop_index(op.f('ix_booking_status_history_booking_id'), table_name='booking_status_history')
    op.drop_table('booking_status_history')
    op.drop_index(op.f('ix_booking_payments_transaction_type'), table_name='booking_payments')
    op.drop_index(op.f('ix_booking_payments_transaction_id'), table_name='booking_payments')
    op.drop_index(op.f('ix_booking_payments_status'), table_name='booking_payments')
    op.drop_index(op.f('ix_booking_payments_payment_method'), table_name='booking_payments')
    op.drop_index(op.f('ix_booking_payments_gateway_payment_id'), table_name='booking_payments')
    op.drop_index(op.f('ix_booking_payments_gateway_order_id'), table_name='booking_payments')
    op.drop_index(op.f('ix_booking_payments_booking_id'), table_name='booking_payments')
    op.drop_table('booking_payments')
    op.drop_index(op.f('ix_booking_costs_vendor_id'), table_name='booking_costs')
    op.drop_index(op.f('ix_booking_costs_booking_id'), table_name='booking_costs')
    op.drop_table('booking_costs')
    op.drop_index(op.f('ix_quotation_items_quotation_id'), table_name='quotation_items')
    op.drop_index(op.f('ix_quotation_items_item_type'), table_name='quotation_items')
    op.drop_table('quotation_items')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_source'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_sales_account_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_quotation_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_enquiry_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_departure_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_created_by'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_code'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_quotations_variant_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_status'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_quotation_code'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_package_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_enquiry_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_customer_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_created_by_account_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_tour_offer_packages_variant_id'), table_name='tour_offer_packages')
    op.drop_index(op.f('ix_tour_offer_packages_offer_id'), table_name='tour_offer_packages')
    op.drop_table('tour_offer_packages')
    op.drop_index(op.f('ix_tour_departures_variant_id'), table_name='tour_departures')
    op.drop_index(op.f('ix_tour_departures_departure_date'), table_name='tour_departures')
    op.drop_table('tour_departures')
    op.drop_index(op.f('ix_notification_campaigns_recipient_id'), table_name='notification_campaigns')
    op.drop_index(op.f('ix_notification_campaigns_notification_id'), table_name='notification_campaigns')
    op.drop_index(op.f('ix_notification_campaigns_is_read'), table_name='notification_campaigns')
    op.drop_index(op.f('ix_notification_campaigns_is_delivered'), table_name='notification_campaigns')
    op.drop_table('notification_campaigns')
    op.drop_index(op.f('ix_expenses_vendor_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_payment_method'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_category'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_created_by_account_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_customer_profiles_referral_code'), table_name='customer_profiles')
    op.drop_table('customer_profiles')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_vendors_vendor_code'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_tour_offers_code'), table_name='tour_offers')
    op.drop_table('tour_offers')
    op.drop_table('hotels')
    op.drop_index(op.f('ix_destinations_slug'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_name'), table_name='destinations')
    op.drop_table('destinations')
    op.drop_index(op.f('ix_accounts_role'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_mobile'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_code'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
