"""remove unwanted fields

Revision ID: f40d84aaf6f0
Revises: c7a1d2e3f4b5
Create Date: 2026-08-22 21:32:43.278763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40d84aaf6f0'
down_revision: Union[str, Sequence[str], None] = 'c7a1d2e3f4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('enquirer_name', sa.String(length=50), nullable=True))
    op.add_column('enquiries', sa.Column('enquirer_phone', sa.String(length=20), nullable=True))
    op.drop_index(op.f('ix_lead_activities_lead_id'), table_name='lead_activities')
    op.drop_constraint(op.f('lead_activities_lead_id_fkey'), 'lead_activities', type_='foreignkey')
    op.drop_column('lead_activities', 'lead_id')
    op.drop_constraint(op.f('ck_tour_details_banner_json_type'), 'tour_details', type_='check')
    op.drop_constraint(op.f('ck_tour_details_departures_dates_is_array'), 'tour_details', type_='check')
    op.drop_constraint(op.f('ck_tour_details_exclusions_is_array'), 'tour_details', type_='check')
    op.drop_constraint(op.f('ck_tour_details_gallery_is_array'), 'tour_details', type_='check')
    op.drop_constraint(op.f('ck_tour_details_highlights_is_array'), 'tour_details', type_='check')
    op.drop_constraint(op.f('ck_tour_details_inclusions_is_array'), 'tour_details', type_='check')
    op.drop_constraint(op.f('ck_tour_details_itinerary_is_array'), 'tour_details', type_='check')
    op.drop_constraint(op.f('ck_tour_details_route_stops_is_array'), 'tour_details', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('ck_tour_details_route_stops_is_array'), 'tour_details', "jsonb_typeof(route_stops) = 'array'::text")
    op.create_check_constraint(op.f('ck_tour_details_itinerary_is_array'), 'tour_details', "jsonb_typeof(itinerary) = 'array'::text")
    op.create_check_constraint(op.f('ck_tour_details_inclusions_is_array'), 'tour_details', "jsonb_typeof(inclusions) = 'array'::text")
    op.create_check_constraint(op.f('ck_tour_details_highlights_is_array'), 'tour_details', "jsonb_typeof(highlights) = 'array'::text")
    op.create_check_constraint(op.f('ck_tour_details_gallery_is_array'), 'tour_details', "jsonb_typeof(gallery) = 'array'::text")
    op.create_check_constraint(op.f('ck_tour_details_exclusions_is_array'), 'tour_details', "jsonb_typeof(exclusions) = 'array'::text")
    op.create_check_constraint(op.f('ck_tour_details_departures_dates_is_array'), 'tour_details', "jsonb_typeof(departures_dates) = 'array'::text")
    op.create_check_constraint(op.f('ck_tour_details_banner_json_type'), 'tour_details', "jsonb_typeof(banner) = ANY (ARRAY['string'::text, 'object'::text])")
    op.add_column('lead_activities', sa.Column('lead_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('lead_activities_lead_id_fkey'), 'lead_activities', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_lead_activities_lead_id'), 'lead_activities', ['lead_id'], unique=False)
    op.drop_column('enquiries', 'enquirer_phone')
    op.drop_column('enquiries', 'enquirer_name')
    # ### end Alembic commands ###
