"""update_schema_to_match_lead_system

Revision ID: fbefd40eb1fa
Revises: f41dbccc14e3
Create Date: 2026-08-15 16:47:37.962854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'fbefd40eb1fa'
down_revision: Union[str, Sequence[str], None] = 'f41dbccc14e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create required PostgreSQL ENUM types if not present
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
                CREATE TYPE user_role AS ENUM ('ADMIN', 'STAFF');
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'lead_status') THEN
                CREATE TYPE lead_status AS ENUM ('NEW', 'CONTACTED', 'FOLLOW_UP', 'QUALIFIED', 'CONVERTED', 'LOST');
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enquiry_type') THEN
                CREATE TYPE enquiry_type AS ENUM ('FIXED_TOUR', 'CUSTOM_TOUR', 'GENERAL');
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enquiry_channel') THEN
                CREATE TYPE enquiry_channel AS ENUM ('WEBSITE', 'WHATSAPP', 'PHONE', 'EMAIL', 'OFFLINE', 'ADMIN');
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enquiry_status') THEN
                CREATE TYPE enquiry_status AS ENUM ('NEW', 'IN_PROGRESS', 'QUOTED', 'CONVERTED', 'CANCELLED', 'CLOSED');
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'lead_source') THEN
                CREATE TYPE lead_source AS ENUM ('WEBSITE', 'WHATSAPP', 'PHONE', 'EMAIL', 'OFFLINE', 'IMPORT', 'REFERRAL', 'OTHER');
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'booking_status') THEN
                CREATE TYPE booking_status AS ENUM ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED');
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'booking_type') THEN
                CREATE TYPE booking_type AS ENUM ('TOUR_PACKAGE', 'CUSTOM_TOUR', 'ROOM_BOOKING');
            END IF;
        END $$;
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiries',

    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enquiry_code', sa.String(length=20), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('enquiry_type', postgresql.ENUM('FIXED_TOUR', 'CUSTOM_TOUR', 'GENERAL', name='enquiry_type', create_type=False), nullable=False),
    sa.Column('channel', postgresql.ENUM('WEBSITE', 'WHATSAPP', 'PHONE', 'EMAIL', 'OFFLINE', 'ADMIN', name='enquiry_channel', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('NEW', 'IN_PROGRESS', 'QUOTED', 'CONVERTED', 'CANCELLED', 'CLOSED', name='enquiry_status', create_type=False), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['package_id'], ['tour_packages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['tour_variants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enquiries_customer_id'), 'enquiries', ['customer_id'], unique=False)
    op.create_index(op.f('ix_enquiries_enquiry_code'), 'enquiries', ['enquiry_code'], unique=True)
    op.create_index(op.f('ix_enquiries_package_id'), 'enquiries', ['package_id'], unique=False)
    op.create_index(op.f('ix_enquiries_status'), 'enquiries', ['status'], unique=False)
    op.create_index(op.f('ix_enquiries_variant_id'), 'enquiries', ['variant_id'], unique=False)
    op.create_index(op.f('ix_enquiries_visitor_id'), 'enquiries', ['visitor_id'], unique=False)
    op.create_table('lead_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('channel', postgresql.ENUM('WEBSITE', 'WHATSAPP', 'PHONE', 'EMAIL', 'OFFLINE', 'ADMIN', name='enquiry_channel', create_type=False), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_activities_lead_id'), 'lead_activities', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_activities_next_follow_up_at'), 'lead_activities', ['next_follow_up_at'], unique=False)
    op.add_column('custom_tour_requests', sa.Column('enquiry_id', sa.UUID(), nullable=True))
    op.add_column('custom_tour_requests', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_custom_tour_requests_customer_id'), 'custom_tour_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_custom_tour_requests_visitor_id'), 'custom_tour_requests', ['visitor_id'], unique=False)
    op.create_foreign_key(None, 'custom_tour_requests', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'custom_tour_requests', 'enquiries', ['enquiry_id'], ['id'], ondelete='SET NULL')
    op.add_column('customers', sa.Column('source', postgresql.ENUM('WEBSITE', 'WHATSAPP', 'PHONE', 'EMAIL', 'OFFLINE', 'IMPORT', 'REFERRAL', 'OTHER', name='lead_source', create_type=False), nullable=False))
    op.add_column('customers', sa.Column('is_imported', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_customers_lead_id'), table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_mobile'), 'customers', ['mobile'], unique=False)
    op.drop_constraint(op.f('customers_lead_id_fkey'), 'customers', type_='foreignkey')
    op.drop_column('customers', 'lead_id')
    op.add_column('leads', sa.Column('enquiry_id', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('visitor_id', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('source', postgresql.ENUM('WEBSITE', 'WHATSAPP', 'PHONE', 'EMAIL', 'OFFLINE', 'IMPORT', 'REFERRAL', 'OTHER', name='lead_source', create_type=False), nullable=False))
    op.alter_column('leads', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=postgresql.ENUM('NEW', 'CONTACTED', 'FOLLOW_UP', 'QUALIFIED', 'CONVERTED', 'LOST', name='lead_status', create_type=False),
               existing_nullable=False,
               postgresql_using='status::lead_status')



    op.drop_index(op.f('ix_leads_mobile'), table_name='leads')
    op.create_index(op.f('ix_leads_mobile'), 'leads', ['mobile'], unique=False)
    op.create_index(op.f('ix_leads_customer_id'), 'leads', ['customer_id'], unique=False)
    op.create_index(op.f('ix_leads_enquiry_id'), 'leads', ['enquiry_id'], unique=False)
    op.create_index(op.f('ix_leads_source'), 'leads', ['source'], unique=False)
    op.create_index(op.f('ix_leads_visitor_id'), 'leads', ['visitor_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'leads', 'enquiries', ['enquiry_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'leads', 'visitors', ['visitor_id'], ['id'], ondelete='SET NULL')
    op.add_column('visitors', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_visitors_lead_id'), table_name='visitors')
    op.create_index(op.f('ix_visitors_customer_id'), 'visitors', ['customer_id'], unique=False)
    op.drop_constraint(op.f('visitors_lead_id_fkey'), 'visitors', type_='foreignkey')
    op.create_foreign_key(None, 'visitors', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.drop_column('visitors', 'lead_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitors', sa.Column('lead_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'visitors', type_='foreignkey')
    op.create_foreign_key(op.f('visitors_lead_id_fkey'), 'visitors', 'leads', ['lead_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_visitors_customer_id'), table_name='visitors')
    op.create_index(op.f('ix_visitors_lead_id'), 'visitors', ['lead_id'], unique=False)
    op.drop_column('visitors', 'customer_id')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_visitor_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_source'), table_name='leads')
    op.drop_index(op.f('ix_leads_enquiry_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_customer_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_mobile'), table_name='leads')
    op.create_index(op.f('ix_leads_mobile'), 'leads', ['mobile'], unique=True)
    op.alter_column('leads', 'status',
               existing_type=sa.Enum('NEW', 'CONTACTED', 'FOLLOW_UP', 'QUALIFIED', 'CONVERTED', 'LOST', name='lead_status'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('leads', 'source')
    op.drop_column('leads', 'visitor_id')
    op.drop_column('leads', 'customer_id')
    op.drop_column('leads', 'enquiry_id')
    op.add_column('customers', sa.Column('lead_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('customers_lead_id_fkey'), 'customers', 'leads', ['lead_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_customers_mobile'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index(op.f('ix_customers_lead_id'), 'customers', ['lead_id'], unique=True)
    op.drop_column('customers', 'is_imported')
    op.drop_column('customers', 'source')
    op.drop_constraint(None, 'custom_tour_requests', type_='foreignkey')
    op.drop_constraint(None, 'custom_tour_requests', type_='foreignkey')
    op.drop_index(op.f('ix_custom_tour_requests_visitor_id'), table_name='custom_tour_requests')
    op.drop_index(op.f('ix_custom_tour_requests_customer_id'), table_name='custom_tour_requests')
    op.drop_column('custom_tour_requests', 'customer_id')
    op.drop_column('custom_tour_requests', 'enquiry_id')
    op.drop_index(op.f('ix_lead_activities_next_follow_up_at'), table_name='lead_activities')
    op.drop_index(op.f('ix_lead_activities_lead_id'), table_name='lead_activities')
    op.drop_table('lead_activities')
    op.drop_index(op.f('ix_enquiries_visitor_id'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_variant_id'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_status'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_package_id'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_enquiry_code'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_customer_id'), table_name='enquiries')
    op.drop_table('enquiries')
    # ### end Alembic commands ###
